provider: akamai
lint: false
major-version: 10
esc:
    enabled: true
env:
    AKAMAI_HOST: ${{ secrets.AKAMAI_HOST }}
    AKAMAI_ACCESS_TOKEN: ${{ secrets.AKAMAI_ACCESS_TOKEN }}
    AKAMAI_CLIENT_TOKEN: ${{ secrets.AKAMAI_CLIENT_TOKEN }}
    AKAMAI_CLIENT_SECRET: ${{ secrets.AKAMAI_CLIENT_SECRET }}
makeTemplate: bridged
pulumiConvert: 1
