provider: akamai
lint: false
major-version: 9
esc:
    enabled: true
env:
    AKAMAI_HOST: ${{ secrets.AKAMAI_HOST }}
    AKAMAI_ACCESS_TOKEN: ${{ secrets.AKAMAI_ACCESS_TOKEN }}
    AKAMAI_CLIENT_TOKEN: ${{ secrets.AKAMAI_CLIENT_TOKEN }}
    AKAMAI_CLIENT_SECRET: ${{ secrets.AKAMAI_CLIENT_SECRET }}
makeTemplate: bridged
plugins:
    - name: terraform
      version: "1.0.16"
      kind: converter
pulumiConvert: 1
