// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai
{
    /// <summary>
    /// **Scopes**: Reputation profile
    /// 
    /// Modifies the action taken when a reputation profile is triggered.
    /// 
    /// **Related API Endpoint**: [/appsec/v1/configs/{configId}/versions/{versionNumber}/security-policies/{policyId}/reputation-profiles/{reputationProfileId}](https://techdocs.akamai.com/application-security/reference/put-reputation-profile-action)
    /// 
    /// ## Example Usage
    /// 
    /// Basic usage:
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Akamai = Pulumi.Akamai;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var configuration = Output.Create(Akamai.GetAppSecConfiguration.InvokeAsync(new Akamai.GetAppSecConfigurationArgs
    ///         {
    ///             Name = "Documentation",
    ///         }));
    ///         var appsecReputationProfileAction = new Akamai.AppSecReputationProfileAction("appsecReputationProfileAction", new Akamai.AppSecReputationProfileActionArgs
    ///         {
    ///             ConfigId = configuration.Apply(configuration =&gt; configuration.ConfigId),
    ///             SecurityPolicyId = "gms1_134637",
    ///             ReputationProfileId = 130713,
    ///             Action = "alert",
    ///         });
    ///         this.ReputationProfileId = appsecReputationProfileAction.ReputationProfileId;
    ///         this.ReputationProfileAction = appsecReputationProfileAction.Action;
    ///     }
    /// 
    ///     [Output("reputationProfileId")]
    ///     public Output&lt;string&gt; ReputationProfileId { get; set; }
    ///     [Output("reputationProfileAction")]
    ///     public Output&lt;string&gt; ReputationProfileAction { get; set; }
    /// }
    /// ```
    /// </summary>
    [AkamaiResourceType("akamai:index/appSecReputationProfileAction:AppSecReputationProfileAction")]
    public partial class AppSecReputationProfileAction : Pulumi.CustomResource
    {
        /// <summary>
        /// . Action taken any time the reputation profile is triggered. Allows values are:
        /// - **alert**. Record the event.
        /// - **deny**. Block the request.
        /// - **deny_custom_{custom_deny_id}**. Take the action specified by the custom deny.
        /// - **none**. Take no action.
        /// </summary>
        [Output("action")]
        public Output<string> Action { get; private set; } = null!;

        /// <summary>
        /// . Unique identifier of the security configuration associated with the reputation profile action being modified.
        /// </summary>
        [Output("configId")]
        public Output<int> ConfigId { get; private set; } = null!;

        /// <summary>
        /// . Unique identifier of the reputation profile whose action is being modified.
        /// </summary>
        [Output("reputationProfileId")]
        public Output<int> ReputationProfileId { get; private set; } = null!;

        /// <summary>
        /// . Unique identifier of the security policy associated with the reputation profile action being modified.
        /// </summary>
        [Output("securityPolicyId")]
        public Output<string> SecurityPolicyId { get; private set; } = null!;


        /// <summary>
        /// Create a AppSecReputationProfileAction resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AppSecReputationProfileAction(string name, AppSecReputationProfileActionArgs args, CustomResourceOptions? options = null)
            : base("akamai:index/appSecReputationProfileAction:AppSecReputationProfileAction", name, args ?? new AppSecReputationProfileActionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AppSecReputationProfileAction(string name, Input<string> id, AppSecReputationProfileActionState? state = null, CustomResourceOptions? options = null)
            : base("akamai:index/appSecReputationProfileAction:AppSecReputationProfileAction", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AppSecReputationProfileAction resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AppSecReputationProfileAction Get(string name, Input<string> id, AppSecReputationProfileActionState? state = null, CustomResourceOptions? options = null)
        {
            return new AppSecReputationProfileAction(name, id, state, options);
        }
    }

    public sealed class AppSecReputationProfileActionArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// . Action taken any time the reputation profile is triggered. Allows values are:
        /// - **alert**. Record the event.
        /// - **deny**. Block the request.
        /// - **deny_custom_{custom_deny_id}**. Take the action specified by the custom deny.
        /// - **none**. Take no action.
        /// </summary>
        [Input("action", required: true)]
        public Input<string> Action { get; set; } = null!;

        /// <summary>
        /// . Unique identifier of the security configuration associated with the reputation profile action being modified.
        /// </summary>
        [Input("configId", required: true)]
        public Input<int> ConfigId { get; set; } = null!;

        /// <summary>
        /// . Unique identifier of the reputation profile whose action is being modified.
        /// </summary>
        [Input("reputationProfileId", required: true)]
        public Input<int> ReputationProfileId { get; set; } = null!;

        /// <summary>
        /// . Unique identifier of the security policy associated with the reputation profile action being modified.
        /// </summary>
        [Input("securityPolicyId", required: true)]
        public Input<string> SecurityPolicyId { get; set; } = null!;

        public AppSecReputationProfileActionArgs()
        {
        }
    }

    public sealed class AppSecReputationProfileActionState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// . Action taken any time the reputation profile is triggered. Allows values are:
        /// - **alert**. Record the event.
        /// - **deny**. Block the request.
        /// - **deny_custom_{custom_deny_id}**. Take the action specified by the custom deny.
        /// - **none**. Take no action.
        /// </summary>
        [Input("action")]
        public Input<string>? Action { get; set; }

        /// <summary>
        /// . Unique identifier of the security configuration associated with the reputation profile action being modified.
        /// </summary>
        [Input("configId")]
        public Input<int>? ConfigId { get; set; }

        /// <summary>
        /// . Unique identifier of the reputation profile whose action is being modified.
        /// </summary>
        [Input("reputationProfileId")]
        public Input<int>? ReputationProfileId { get; set; }

        /// <summary>
        /// . Unique identifier of the security policy associated with the reputation profile action being modified.
        /// </summary>
        [Input("securityPolicyId")]
        public Input<string>? SecurityPolicyId { get; set; }

        public AppSecReputationProfileActionState()
        {
        }
    }
}
