// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai
{
    [AkamaiResourceType("akamai:index/appsecUrlProtectionPolicy:AppsecUrlProtectionPolicy")]
    public partial class AppsecUrlProtectionPolicy : global::Pulumi.CustomResource
    {
        /// <summary>
        /// List of API definitions associated with the URL protection policy
        /// </summary>
        [Output("apiDefinitions")]
        public Output<ImmutableArray<Outputs.AppsecUrlProtectionPolicyApiDefinition>> ApiDefinitions { get; private set; } = null!;

        /// <summary>
        /// List of bypass conditions for the URL protection policy
        /// </summary>
        [Output("bypassConditions")]
        public Output<ImmutableArray<Outputs.AppsecUrlProtectionPolicyBypassCondition>> BypassConditions { get; private set; } = null!;

        /// <summary>
        /// Unique identifier of the security configuration
        /// </summary>
        [Output("configId")]
        public Output<int> ConfigId { get; private set; } = null!;

        /// <summary>
        /// Date when the URL protection policy was created
        /// </summary>
        [Output("createDate")]
        public Output<string> CreateDate { get; private set; } = null!;

        /// <summary>
        /// User who created the URL protection policy
        /// </summary>
        [Output("createdBy")]
        public Output<string> CreatedBy { get; private set; } = null!;

        /// <summary>
        /// Description of the URL protection policy
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// List of hostname and path configurations
        /// </summary>
        [Output("hostnamePaths")]
        public Output<ImmutableArray<Outputs.AppsecUrlProtectionPolicyHostnamePath>> HostnamePaths { get; private set; } = null!;

        /// <summary>
        /// Intelligent load shedding configuration
        /// </summary>
        [Output("intelligentLoadShedding")]
        public Output<Outputs.AppsecUrlProtectionPolicyIntelligentLoadShedding?> IntelligentLoadShedding { get; private set; } = null!;

        /// <summary>
        /// Maximum rate threshold for the URL protection policy
        /// </summary>
        [Output("maxRateThreshold")]
        public Output<int> MaxRateThreshold { get; private set; } = null!;

        /// <summary>
        /// Name of the URL protection policy
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Date when the URL protection policy was last updated
        /// </summary>
        [Output("updateDate")]
        public Output<string> UpdateDate { get; private set; } = null!;

        /// <summary>
        /// User who last updated the URL protection policy
        /// </summary>
        [Output("updatedBy")]
        public Output<string> UpdatedBy { get; private set; } = null!;

        /// <summary>
        /// Unique identifier of the URL protection policy
        /// </summary>
        [Output("urlProtectionPolicyId")]
        public Output<int> UrlProtectionPolicyId { get; private set; } = null!;


        /// <summary>
        /// Create a AppsecUrlProtectionPolicy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AppsecUrlProtectionPolicy(string name, AppsecUrlProtectionPolicyArgs args, CustomResourceOptions? options = null)
            : base("akamai:index/appsecUrlProtectionPolicy:AppsecUrlProtectionPolicy", name, args ?? new AppsecUrlProtectionPolicyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AppsecUrlProtectionPolicy(string name, Input<string> id, AppsecUrlProtectionPolicyState? state = null, CustomResourceOptions? options = null)
            : base("akamai:index/appsecUrlProtectionPolicy:AppsecUrlProtectionPolicy", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AppsecUrlProtectionPolicy resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AppsecUrlProtectionPolicy Get(string name, Input<string> id, AppsecUrlProtectionPolicyState? state = null, CustomResourceOptions? options = null)
        {
            return new AppsecUrlProtectionPolicy(name, id, state, options);
        }
    }

    public sealed class AppsecUrlProtectionPolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiDefinitions")]
        private InputList<Inputs.AppsecUrlProtectionPolicyApiDefinitionArgs>? _apiDefinitions;

        /// <summary>
        /// List of API definitions associated with the URL protection policy
        /// </summary>
        public InputList<Inputs.AppsecUrlProtectionPolicyApiDefinitionArgs> ApiDefinitions
        {
            get => _apiDefinitions ?? (_apiDefinitions = new InputList<Inputs.AppsecUrlProtectionPolicyApiDefinitionArgs>());
            set => _apiDefinitions = value;
        }

        [Input("bypassConditions")]
        private InputList<Inputs.AppsecUrlProtectionPolicyBypassConditionArgs>? _bypassConditions;

        /// <summary>
        /// List of bypass conditions for the URL protection policy
        /// </summary>
        public InputList<Inputs.AppsecUrlProtectionPolicyBypassConditionArgs> BypassConditions
        {
            get => _bypassConditions ?? (_bypassConditions = new InputList<Inputs.AppsecUrlProtectionPolicyBypassConditionArgs>());
            set => _bypassConditions = value;
        }

        /// <summary>
        /// Unique identifier of the security configuration
        /// </summary>
        [Input("configId", required: true)]
        public Input<int> ConfigId { get; set; } = null!;

        /// <summary>
        /// Description of the URL protection policy
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("hostnamePaths")]
        private InputList<Inputs.AppsecUrlProtectionPolicyHostnamePathArgs>? _hostnamePaths;

        /// <summary>
        /// List of hostname and path configurations
        /// </summary>
        public InputList<Inputs.AppsecUrlProtectionPolicyHostnamePathArgs> HostnamePaths
        {
            get => _hostnamePaths ?? (_hostnamePaths = new InputList<Inputs.AppsecUrlProtectionPolicyHostnamePathArgs>());
            set => _hostnamePaths = value;
        }

        /// <summary>
        /// Intelligent load shedding configuration
        /// </summary>
        [Input("intelligentLoadShedding")]
        public Input<Inputs.AppsecUrlProtectionPolicyIntelligentLoadSheddingArgs>? IntelligentLoadShedding { get; set; }

        /// <summary>
        /// Maximum rate threshold for the URL protection policy
        /// </summary>
        [Input("maxRateThreshold", required: true)]
        public Input<int> MaxRateThreshold { get; set; } = null!;

        /// <summary>
        /// Name of the URL protection policy
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public AppsecUrlProtectionPolicyArgs()
        {
        }
        public static new AppsecUrlProtectionPolicyArgs Empty => new AppsecUrlProtectionPolicyArgs();
    }

    public sealed class AppsecUrlProtectionPolicyState : global::Pulumi.ResourceArgs
    {
        [Input("apiDefinitions")]
        private InputList<Inputs.AppsecUrlProtectionPolicyApiDefinitionGetArgs>? _apiDefinitions;

        /// <summary>
        /// List of API definitions associated with the URL protection policy
        /// </summary>
        public InputList<Inputs.AppsecUrlProtectionPolicyApiDefinitionGetArgs> ApiDefinitions
        {
            get => _apiDefinitions ?? (_apiDefinitions = new InputList<Inputs.AppsecUrlProtectionPolicyApiDefinitionGetArgs>());
            set => _apiDefinitions = value;
        }

        [Input("bypassConditions")]
        private InputList<Inputs.AppsecUrlProtectionPolicyBypassConditionGetArgs>? _bypassConditions;

        /// <summary>
        /// List of bypass conditions for the URL protection policy
        /// </summary>
        public InputList<Inputs.AppsecUrlProtectionPolicyBypassConditionGetArgs> BypassConditions
        {
            get => _bypassConditions ?? (_bypassConditions = new InputList<Inputs.AppsecUrlProtectionPolicyBypassConditionGetArgs>());
            set => _bypassConditions = value;
        }

        /// <summary>
        /// Unique identifier of the security configuration
        /// </summary>
        [Input("configId")]
        public Input<int>? ConfigId { get; set; }

        /// <summary>
        /// Date when the URL protection policy was created
        /// </summary>
        [Input("createDate")]
        public Input<string>? CreateDate { get; set; }

        /// <summary>
        /// User who created the URL protection policy
        /// </summary>
        [Input("createdBy")]
        public Input<string>? CreatedBy { get; set; }

        /// <summary>
        /// Description of the URL protection policy
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("hostnamePaths")]
        private InputList<Inputs.AppsecUrlProtectionPolicyHostnamePathGetArgs>? _hostnamePaths;

        /// <summary>
        /// List of hostname and path configurations
        /// </summary>
        public InputList<Inputs.AppsecUrlProtectionPolicyHostnamePathGetArgs> HostnamePaths
        {
            get => _hostnamePaths ?? (_hostnamePaths = new InputList<Inputs.AppsecUrlProtectionPolicyHostnamePathGetArgs>());
            set => _hostnamePaths = value;
        }

        /// <summary>
        /// Intelligent load shedding configuration
        /// </summary>
        [Input("intelligentLoadShedding")]
        public Input<Inputs.AppsecUrlProtectionPolicyIntelligentLoadSheddingGetArgs>? IntelligentLoadShedding { get; set; }

        /// <summary>
        /// Maximum rate threshold for the URL protection policy
        /// </summary>
        [Input("maxRateThreshold")]
        public Input<int>? MaxRateThreshold { get; set; }

        /// <summary>
        /// Name of the URL protection policy
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Date when the URL protection policy was last updated
        /// </summary>
        [Input("updateDate")]
        public Input<string>? UpdateDate { get; set; }

        /// <summary>
        /// User who last updated the URL protection policy
        /// </summary>
        [Input("updatedBy")]
        public Input<string>? UpdatedBy { get; set; }

        /// <summary>
        /// Unique identifier of the URL protection policy
        /// </summary>
        [Input("urlProtectionPolicyId")]
        public Input<int>? UrlProtectionPolicyId { get; set; }

        public AppsecUrlProtectionPolicyState()
        {
        }
        public static new AppsecUrlProtectionPolicyState Empty => new AppsecUrlProtectionPolicyState();
    }
}
