// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai
{
    public static class GetAppsecUrlProtectionPolicies
    {
        public static Task<GetAppsecUrlProtectionPoliciesResult> InvokeAsync(GetAppsecUrlProtectionPoliciesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAppsecUrlProtectionPoliciesResult>("akamai:index/getAppsecUrlProtectionPolicies:getAppsecUrlProtectionPolicies", args ?? new GetAppsecUrlProtectionPoliciesArgs(), options.WithDefaults());

        public static Output<GetAppsecUrlProtectionPoliciesResult> Invoke(GetAppsecUrlProtectionPoliciesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAppsecUrlProtectionPoliciesResult>("akamai:index/getAppsecUrlProtectionPolicies:getAppsecUrlProtectionPolicies", args ?? new GetAppsecUrlProtectionPoliciesInvokeArgs(), options.WithDefaults());

        public static Output<GetAppsecUrlProtectionPoliciesResult> Invoke(GetAppsecUrlProtectionPoliciesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAppsecUrlProtectionPoliciesResult>("akamai:index/getAppsecUrlProtectionPolicies:getAppsecUrlProtectionPolicies", args ?? new GetAppsecUrlProtectionPoliciesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAppsecUrlProtectionPoliciesArgs : global::Pulumi.InvokeArgs
    {
        [Input("configId", required: true)]
        public int ConfigId { get; set; }

        public GetAppsecUrlProtectionPoliciesArgs()
        {
        }
        public static new GetAppsecUrlProtectionPoliciesArgs Empty => new GetAppsecUrlProtectionPoliciesArgs();
    }

    public sealed class GetAppsecUrlProtectionPoliciesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("configId", required: true)]
        public Input<int> ConfigId { get; set; } = null!;

        public GetAppsecUrlProtectionPoliciesInvokeArgs()
        {
        }
        public static new GetAppsecUrlProtectionPoliciesInvokeArgs Empty => new GetAppsecUrlProtectionPoliciesInvokeArgs();
    }


    [OutputType]
    public sealed class GetAppsecUrlProtectionPoliciesResult
    {
        public readonly int ConfigId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetAppsecUrlProtectionPoliciesUrlProtectionPolicyResult> UrlProtectionPolicies;

        [OutputConstructor]
        private GetAppsecUrlProtectionPoliciesResult(
            int configId,

            string id,

            ImmutableArray<Outputs.GetAppsecUrlProtectionPoliciesUrlProtectionPolicyResult> urlProtectionPolicies)
        {
            ConfigId = configId;
            Id = id;
            UrlProtectionPolicies = urlProtectionPolicies;
        }
    }
}
