// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DatastreamSumologicConnector {
    /**
     * @return **Secret**. The unique HTTP collector code of your Sumo Logic `endpoint`.
     * 
     */
    private String collectorCode;
    /**
     * @return Enables GZIP compression for a log file sent to a destination. If unspecified, this defaults to `true`.
     * 
     */
    private @Nullable Boolean compressLogs;
    private @Nullable Integer connectorId;
    /**
     * @return The name of the connector.
     * 
     */
    private String connectorName;
    /**
     * @return The Sumo Logic collection endpoint where you want to send your logs. You should follow the `https://&lt;SumoEndpoint&gt;/receiver/v1/http` format and pass the collector code in the `collectorCode` argument.
     * 
     */
    private String endpoint;

    private DatastreamSumologicConnector() {}
    /**
     * @return **Secret**. The unique HTTP collector code of your Sumo Logic `endpoint`.
     * 
     */
    public String collectorCode() {
        return this.collectorCode;
    }
    /**
     * @return Enables GZIP compression for a log file sent to a destination. If unspecified, this defaults to `true`.
     * 
     */
    public Optional<Boolean> compressLogs() {
        return Optional.ofNullable(this.compressLogs);
    }
    public Optional<Integer> connectorId() {
        return Optional.ofNullable(this.connectorId);
    }
    /**
     * @return The name of the connector.
     * 
     */
    public String connectorName() {
        return this.connectorName;
    }
    /**
     * @return The Sumo Logic collection endpoint where you want to send your logs. You should follow the `https://&lt;SumoEndpoint&gt;/receiver/v1/http` format and pass the collector code in the `collectorCode` argument.
     * 
     */
    public String endpoint() {
        return this.endpoint;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DatastreamSumologicConnector defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String collectorCode;
        private @Nullable Boolean compressLogs;
        private @Nullable Integer connectorId;
        private String connectorName;
        private String endpoint;
        public Builder() {}
        public Builder(DatastreamSumologicConnector defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.collectorCode = defaults.collectorCode;
    	      this.compressLogs = defaults.compressLogs;
    	      this.connectorId = defaults.connectorId;
    	      this.connectorName = defaults.connectorName;
    	      this.endpoint = defaults.endpoint;
        }

        @CustomType.Setter
        public Builder collectorCode(String collectorCode) {
            this.collectorCode = Objects.requireNonNull(collectorCode);
            return this;
        }
        @CustomType.Setter
        public Builder compressLogs(@Nullable Boolean compressLogs) {
            this.compressLogs = compressLogs;
            return this;
        }
        @CustomType.Setter
        public Builder connectorId(@Nullable Integer connectorId) {
            this.connectorId = connectorId;
            return this;
        }
        @CustomType.Setter
        public Builder connectorName(String connectorName) {
            this.connectorName = Objects.requireNonNull(connectorName);
            return this;
        }
        @CustomType.Setter
        public Builder endpoint(String endpoint) {
            this.endpoint = Objects.requireNonNull(endpoint);
            return this;
        }
        public DatastreamSumologicConnector build() {
            final var o = new DatastreamSumologicConnector();
            o.collectorCode = collectorCode;
            o.compressLogs = compressLogs;
            o.connectorId = connectorId;
            o.connectorName = connectorName;
            o.endpoint = endpoint;
            return o;
        }
    }
}
