// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.outputs;

import com.pulumi.core.annotations.CustomType;
import java.util.Objects;

@CustomType
public final class GetImagingPolicyImagePolicyPostBreakpointTransformationCompoundTransformationIfDimensionGreaterThanIfDimensionEqual {
    private GetImagingPolicyImagePolicyPostBreakpointTransformationCompoundTransformationIfDimensionGreaterThanIfDimensionEqual() {}

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetImagingPolicyImagePolicyPostBreakpointTransformationCompoundTransformationIfDimensionGreaterThanIfDimensionEqual defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        public Builder() {}
        public Builder(GetImagingPolicyImagePolicyPostBreakpointTransformationCompoundTransformationIfDimensionGreaterThanIfDimensionEqual defaults) {
    	      Objects.requireNonNull(defaults);
        }

        public GetImagingPolicyImagePolicyPostBreakpointTransformationCompoundTransformationIfDimensionGreaterThanIfDimensionEqual build() {
            final var o = new GetImagingPolicyImagePolicyPostBreakpointTransformationCompoundTransformationIfDimensionGreaterThanIfDimensionEqual();
            return o;
        }
    }
}
