// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.outputs;

import com.pulumi.akamai.outputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationDefault;
import com.pulumi.akamai.outputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationLandscape;
import com.pulumi.akamai.outputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationPortrait;
import com.pulumi.akamai.outputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationSquare;
import com.pulumi.core.annotations.CustomType;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientation {
    private @Nullable GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationDefault default_;
    private @Nullable GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationLandscape landscape;
    private @Nullable GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationPortrait portrait;
    private @Nullable GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationSquare square;

    private GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientation() {}
    public Optional<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationDefault> default_() {
        return Optional.ofNullable(this.default_);
    }
    public Optional<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationLandscape> landscape() {
        return Optional.ofNullable(this.landscape);
    }
    public Optional<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationPortrait> portrait() {
        return Optional.ofNullable(this.portrait);
    }
    public Optional<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationSquare> square() {
        return Optional.ofNullable(this.square);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientation defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationDefault default_;
        private @Nullable GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationLandscape landscape;
        private @Nullable GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationPortrait portrait;
        private @Nullable GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationSquare square;
        public Builder() {}
        public Builder(GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientation defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.default_ = defaults.default_;
    	      this.landscape = defaults.landscape;
    	      this.portrait = defaults.portrait;
    	      this.square = defaults.square;
        }

        @CustomType.Setter("default")
        public Builder default_(@Nullable GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationDefault default_) {
            this.default_ = default_;
            return this;
        }
        @CustomType.Setter
        public Builder landscape(@Nullable GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationLandscape landscape) {
            this.landscape = landscape;
            return this;
        }
        @CustomType.Setter
        public Builder portrait(@Nullable GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationPortrait portrait) {
            this.portrait = portrait;
            return this;
        }
        @CustomType.Setter
        public Builder square(@Nullable GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationSquare square) {
            this.square = square;
            return this;
        }
        public GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientation build() {
            final var o = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientation();
            o.default_ = default_;
            o.landscape = landscape;
            o.portrait = portrait;
            o.square = square;
            return o;
        }
    }
}
