// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.outputs;

import com.pulumi.akamai.outputs.GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationDefault;
import com.pulumi.akamai.outputs.GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationLandscape;
import com.pulumi.akamai.outputs.GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationPortrait;
import com.pulumi.akamai.outputs.GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationSquare;
import com.pulumi.core.annotations.CustomType;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientation {
    private @Nullable GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationDefault default_;
    private @Nullable GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationLandscape landscape;
    private @Nullable GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationPortrait portrait;
    private @Nullable GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationSquare square;

    private GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientation() {}
    public Optional<GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationDefault> default_() {
        return Optional.ofNullable(this.default_);
    }
    public Optional<GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationLandscape> landscape() {
        return Optional.ofNullable(this.landscape);
    }
    public Optional<GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationPortrait> portrait() {
        return Optional.ofNullable(this.portrait);
    }
    public Optional<GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationSquare> square() {
        return Optional.ofNullable(this.square);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientation defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationDefault default_;
        private @Nullable GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationLandscape landscape;
        private @Nullable GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationPortrait portrait;
        private @Nullable GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationSquare square;
        public Builder() {}
        public Builder(GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientation defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.default_ = defaults.default_;
    	      this.landscape = defaults.landscape;
    	      this.portrait = defaults.portrait;
    	      this.square = defaults.square;
        }

        @CustomType.Setter("default")
        public Builder default_(@Nullable GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationDefault default_) {
            this.default_ = default_;
            return this;
        }
        @CustomType.Setter
        public Builder landscape(@Nullable GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationLandscape landscape) {
            this.landscape = landscape;
            return this;
        }
        @CustomType.Setter
        public Builder portrait(@Nullable GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationPortrait portrait) {
            this.portrait = portrait;
            return this;
        }
        @CustomType.Setter
        public Builder square(@Nullable GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientationSquare square) {
            this.square = square;
            return this;
        }
        public GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientation build() {
            final var o = new GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationDefaultIfOrientation();
            o.default_ = default_;
            o.landscape = landscape;
            o.portrait = portrait;
            o.square = square;
            return o;
        }
    }
}
