// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.outputs;

import com.pulumi.akamai.outputs.GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestCircleShape;
import com.pulumi.akamai.outputs.GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestPointShape;
import com.pulumi.akamai.outputs.GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestPolygonShape;
import com.pulumi.akamai.outputs.GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestRectangleShape;
import com.pulumi.akamai.outputs.GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestUnionShape;
import com.pulumi.core.annotations.CustomType;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterest {
    private @Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestCircleShape> circleShapes;
    private @Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestPointShape> pointShapes;
    private @Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestPolygonShape> polygonShapes;
    private @Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestRectangleShape> rectangleShapes;
    private @Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestUnionShape> unionShapes;

    private GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterest() {}
    public List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestCircleShape> circleShapes() {
        return this.circleShapes == null ? List.of() : this.circleShapes;
    }
    public List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestPointShape> pointShapes() {
        return this.pointShapes == null ? List.of() : this.pointShapes;
    }
    public List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestPolygonShape> polygonShapes() {
        return this.polygonShapes == null ? List.of() : this.polygonShapes;
    }
    public List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestRectangleShape> rectangleShapes() {
        return this.rectangleShapes == null ? List.of() : this.rectangleShapes;
    }
    public List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestUnionShape> unionShapes() {
        return this.unionShapes == null ? List.of() : this.unionShapes;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterest defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestCircleShape> circleShapes;
        private @Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestPointShape> pointShapes;
        private @Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestPolygonShape> polygonShapes;
        private @Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestRectangleShape> rectangleShapes;
        private @Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestUnionShape> unionShapes;
        public Builder() {}
        public Builder(GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterest defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.circleShapes = defaults.circleShapes;
    	      this.pointShapes = defaults.pointShapes;
    	      this.polygonShapes = defaults.polygonShapes;
    	      this.rectangleShapes = defaults.rectangleShapes;
    	      this.unionShapes = defaults.unionShapes;
        }

        @CustomType.Setter
        public Builder circleShapes(@Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestCircleShape> circleShapes) {
            this.circleShapes = circleShapes;
            return this;
        }
        public Builder circleShapes(GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestCircleShape... circleShapes) {
            return circleShapes(List.of(circleShapes));
        }
        @CustomType.Setter
        public Builder pointShapes(@Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestPointShape> pointShapes) {
            this.pointShapes = pointShapes;
            return this;
        }
        public Builder pointShapes(GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestPointShape... pointShapes) {
            return pointShapes(List.of(pointShapes));
        }
        @CustomType.Setter
        public Builder polygonShapes(@Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestPolygonShape> polygonShapes) {
            this.polygonShapes = polygonShapes;
            return this;
        }
        public Builder polygonShapes(GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestPolygonShape... polygonShapes) {
            return polygonShapes(List.of(polygonShapes));
        }
        @CustomType.Setter
        public Builder rectangleShapes(@Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestRectangleShape> rectangleShapes) {
            this.rectangleShapes = rectangleShapes;
            return this;
        }
        public Builder rectangleShapes(GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestRectangleShape... rectangleShapes) {
            return rectangleShapes(List.of(rectangleShapes));
        }
        @CustomType.Setter
        public Builder unionShapes(@Nullable List<GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestUnionShape> unionShapes) {
            this.unionShapes = unionShapes;
            return this;
        }
        public Builder unionShapes(GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterestUnionShape... unionShapes) {
            return unionShapes(List.of(unionShapes));
        }
        public GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterest build() {
            final var o = new GetImagingPolicyImagePolicyTransformationIfOrientationLandscapeRegionOfInterestCropRegionOfInterest();
            o.circleShapes = circleShapes;
            o.pointShapes = pointShapes;
            o.polygonShapes = polygonShapes;
            o.rectangleShapes = rectangleShapes;
            o.unionShapes = unionShapes;
            return o;
        }
    }
}
