// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetPropertyRulesBuilderRulesV20231030BehaviorMediaOriginFailover {
    /**
     * @return When enabled, caches the error response.
     * 
     */
    private @Nullable Boolean cacheErrorResponse;
    /**
     * @return This sets error response&#39;s TTL.
     * 
     */
    private @Nullable String cacheWindow;
    /**
     * @return Specifies the response code served to the client.
     * 
     */
    private @Nullable String clientResponseCode;
    /**
     * @return Allows you to configure failover settings when the origin has content errors.
     * 
     */
    private @Nullable Boolean detectObjectUnavailable;
    /**
     * @return This field is only intended for export compatibility purposes, and modifying it will not impact your use of the behavior.
     * 
     */
    private @Nullable String detectObjectUnavailableTitle;
    /**
     * @return Allows you to configure failover settings when the origin server responds with errors.
     * 
     */
    private @Nullable Boolean detectOriginUnavailable;
    /**
     * @return This field is only intended for export compatibility purposes, and modifying it will not impact your use of the behavior.
     * 
     */
    private @Nullable String detectOriginUnavailableTitle;
    /**
     * @return Allows you to configure what happens when the origin is unresponsive.
     * 
     */
    private @Nullable Boolean detectOriginUnresponsive;
    /**
     * @return This field is only intended for export compatibility purposes, and modifying it will not impact your use of the behavior.
     * 
     */
    private @Nullable String detectOriginUnresponsiveTitle;
    /**
     * @return Indicates that your Akamai representative has locked this behavior or criteria so that you can&#39;t modify it. This option is for internal usage only.
     * 
     */
    private @Nullable Boolean locked;
    /**
     * @return This specifies the redirect&#39;s destination hostname.
     * 
     */
    private @Nullable String objectUnavailableAlternateHost;
    /**
     * @return This specifies the origin hostname.
     * 
     */
    private @Nullable String objectUnavailableBackupHost;
    /**
     * @return Enabling this blacklists the origin&#39;s IP address.
     * 
     */
    private @Nullable Boolean objectUnavailableBlacklistOriginIp;
    /**
     * @return This sets the delay before blacklisting an IP address.
     * 
     */
    private @Nullable String objectUnavailableBlacklistWindow;
    /**
     * @return Changes the request protocol.
     * 
     */
    private @Nullable Boolean objectUnavailableChangeProtocol;
    /**
     * @return Specify `RESPONSE_CODES`, the only available option.
     * 
     */
    private @Nullable String objectUnavailableDetectionLevel;
    /**
     * @return Enabling this includes the original set of query parameters.
     * 
     */
    private @Nullable Boolean objectUnavailableIncludeQueryString;
    /**
     * @return This specifies the path to form the new URL.
     * 
     */
    private @Nullable String objectUnavailableModifiedPath;
    /**
     * @return Enabling this allows you to modify the request path.
     * 
     */
    private @Nullable Boolean objectUnavailableModifyRequestPath;
    /**
     * @return Specifies either the `HTTP` or `HTTPS` protocol.
     * 
     */
    private @Nullable String objectUnavailableProtocol;
    /**
     * @return This sets the recovery option.
     * 
     */
    private @Nullable String objectUnavailableRecovery;
    /**
     * @return Specifies a redirect response code.
     * 
     */
    private @Nullable Integer objectUnavailableRedirectMethod;
    /**
     * @return Specifies the set of response codes identifying when there are content errors.
     * 
     */
    private @Nullable List<String> objectUnavailableResponseCodes;
    /**
     * @return Sets how many times to retry.
     * 
     */
    private @Nullable String objectUnavailableRetryLimit;
    /**
     * @return This specifies the redirect&#39;s destination hostname.
     * 
     */
    private @Nullable String originUnavailableAlternateHost;
    /**
     * @return This specifies the origin hostname.
     * 
     */
    private @Nullable String originUnavailableBackupHost;
    /**
     * @return Enabling this blacklists the origin&#39;s IP address.
     * 
     */
    private @Nullable Boolean originUnavailableBlacklistOriginIp;
    /**
     * @return This sets the delay before blacklisting an IP address.
     * 
     */
    private @Nullable String originUnavailableBlacklistWindow;
    /**
     * @return Modifies the request protocol.
     * 
     */
    private @Nullable Boolean originUnavailableChangeProtocol;
    /**
     * @return Specify `RESPONSE_CODES`, the only available option.
     * 
     */
    private @Nullable String originUnavailableDetectionLevel;
    /**
     * @return Enabling this includes the original set of query parameters.
     * 
     */
    private @Nullable Boolean originUnavailableIncludeQueryString;
    /**
     * @return This specifies the path to form the new URL.
     * 
     */
    private @Nullable String originUnavailableModifiedPath;
    /**
     * @return Modifies the request path.
     * 
     */
    private @Nullable Boolean originUnavailableModifyRequestPath;
    /**
     * @return Specifies either the `HTTP` or `HTTPS` protocol.
     * 
     */
    private @Nullable String originUnavailableProtocol;
    /**
     * @return This sets the recovery option.
     * 
     */
    private @Nullable String originUnavailableRecovery;
    /**
     * @return Specifies either a redirect response code.
     * 
     */
    private @Nullable Integer originUnavailableRedirectMethod;
    /**
     * @return Specifies the set of response codes identifying when the origin responds with errors.
     * 
     */
    private @Nullable List<String> originUnavailableResponseCodes;
    /**
     * @return Sets how many times to retry.
     * 
     */
    private @Nullable String originUnavailableRetryLimit;
    /**
     * @return This specifies the redirect&#39;s destination hostname.
     * 
     */
    private @Nullable String originUnresponsiveAlternateHost;
    /**
     * @return This specifies the origin hostname.
     * 
     */
    private @Nullable String originUnresponsiveBackupHost;
    /**
     * @return Enabling this blacklists the origin&#39;s IP address.
     * 
     */
    private @Nullable Boolean originUnresponsiveBlacklistOriginIp;
    /**
     * @return This sets the delay before blacklisting an IP address.
     * 
     */
    private @Nullable String originUnresponsiveBlacklistWindow;
    /**
     * @return This allows you to change the request protocol.
     * 
     */
    private @Nullable Boolean originUnresponsiveChangeProtocol;
    /**
     * @return Specify the level of response to slow origin connections.
     * 
     */
    private @Nullable String originUnresponsiveDetectionLevel;
    /**
     * @return Enabling this includes the original set of query parameters.
     * 
     */
    private @Nullable Boolean originUnresponsiveIncludeQueryString;
    /**
     * @return This specifies the path to form the new URL.
     * 
     */
    private @Nullable String originUnresponsiveModifiedPath;
    /**
     * @return Modifies the request path.
     * 
     */
    private @Nullable Boolean originUnresponsiveModifyRequestPath;
    /**
     * @return Specifies which protocol to use.
     * 
     */
    private @Nullable String originUnresponsiveProtocol;
    /**
     * @return This sets the recovery option.
     * 
     */
    private @Nullable String originUnresponsiveRecovery;
    /**
     * @return Specifies the redirect response code.
     * 
     */
    private @Nullable Integer originUnresponsiveRedirectMethod;
    /**
     * @return Sets how many times to retry.
     * 
     */
    private @Nullable String originUnresponsiveRetryLimit;
    /**
     * @return This field is only intended for export compatibility purposes, and modifying it will not impact your use of the behavior.
     * 
     */
    private @Nullable String otherOptions;
    /**
     * @return This option is for internal usage only.
     * 
     */
    private @Nullable String templateUuid;
    /**
     * @return A uuid member indicates that at least one of its component behaviors or criteria is advanced and read-only. You need to preserve this uuid as well when modifying the rule tree. This option is for internal usage only.
     * 
     */
    private @Nullable String uuid;

    private GetPropertyRulesBuilderRulesV20231030BehaviorMediaOriginFailover() {}
    /**
     * @return When enabled, caches the error response.
     * 
     */
    public Optional<Boolean> cacheErrorResponse() {
        return Optional.ofNullable(this.cacheErrorResponse);
    }
    /**
     * @return This sets error response&#39;s TTL.
     * 
     */
    public Optional<String> cacheWindow() {
        return Optional.ofNullable(this.cacheWindow);
    }
    /**
     * @return Specifies the response code served to the client.
     * 
     */
    public Optional<String> clientResponseCode() {
        return Optional.ofNullable(this.clientResponseCode);
    }
    /**
     * @return Allows you to configure failover settings when the origin has content errors.
     * 
     */
    public Optional<Boolean> detectObjectUnavailable() {
        return Optional.ofNullable(this.detectObjectUnavailable);
    }
    /**
     * @return This field is only intended for export compatibility purposes, and modifying it will not impact your use of the behavior.
     * 
     */
    public Optional<String> detectObjectUnavailableTitle() {
        return Optional.ofNullable(this.detectObjectUnavailableTitle);
    }
    /**
     * @return Allows you to configure failover settings when the origin server responds with errors.
     * 
     */
    public Optional<Boolean> detectOriginUnavailable() {
        return Optional.ofNullable(this.detectOriginUnavailable);
    }
    /**
     * @return This field is only intended for export compatibility purposes, and modifying it will not impact your use of the behavior.
     * 
     */
    public Optional<String> detectOriginUnavailableTitle() {
        return Optional.ofNullable(this.detectOriginUnavailableTitle);
    }
    /**
     * @return Allows you to configure what happens when the origin is unresponsive.
     * 
     */
    public Optional<Boolean> detectOriginUnresponsive() {
        return Optional.ofNullable(this.detectOriginUnresponsive);
    }
    /**
     * @return This field is only intended for export compatibility purposes, and modifying it will not impact your use of the behavior.
     * 
     */
    public Optional<String> detectOriginUnresponsiveTitle() {
        return Optional.ofNullable(this.detectOriginUnresponsiveTitle);
    }
    /**
     * @return Indicates that your Akamai representative has locked this behavior or criteria so that you can&#39;t modify it. This option is for internal usage only.
     * 
     */
    public Optional<Boolean> locked() {
        return Optional.ofNullable(this.locked);
    }
    /**
     * @return This specifies the redirect&#39;s destination hostname.
     * 
     */
    public Optional<String> objectUnavailableAlternateHost() {
        return Optional.ofNullable(this.objectUnavailableAlternateHost);
    }
    /**
     * @return This specifies the origin hostname.
     * 
     */
    public Optional<String> objectUnavailableBackupHost() {
        return Optional.ofNullable(this.objectUnavailableBackupHost);
    }
    /**
     * @return Enabling this blacklists the origin&#39;s IP address.
     * 
     */
    public Optional<Boolean> objectUnavailableBlacklistOriginIp() {
        return Optional.ofNullable(this.objectUnavailableBlacklistOriginIp);
    }
    /**
     * @return This sets the delay before blacklisting an IP address.
     * 
     */
    public Optional<String> objectUnavailableBlacklistWindow() {
        return Optional.ofNullable(this.objectUnavailableBlacklistWindow);
    }
    /**
     * @return Changes the request protocol.
     * 
     */
    public Optional<Boolean> objectUnavailableChangeProtocol() {
        return Optional.ofNullable(this.objectUnavailableChangeProtocol);
    }
    /**
     * @return Specify `RESPONSE_CODES`, the only available option.
     * 
     */
    public Optional<String> objectUnavailableDetectionLevel() {
        return Optional.ofNullable(this.objectUnavailableDetectionLevel);
    }
    /**
     * @return Enabling this includes the original set of query parameters.
     * 
     */
    public Optional<Boolean> objectUnavailableIncludeQueryString() {
        return Optional.ofNullable(this.objectUnavailableIncludeQueryString);
    }
    /**
     * @return This specifies the path to form the new URL.
     * 
     */
    public Optional<String> objectUnavailableModifiedPath() {
        return Optional.ofNullable(this.objectUnavailableModifiedPath);
    }
    /**
     * @return Enabling this allows you to modify the request path.
     * 
     */
    public Optional<Boolean> objectUnavailableModifyRequestPath() {
        return Optional.ofNullable(this.objectUnavailableModifyRequestPath);
    }
    /**
     * @return Specifies either the `HTTP` or `HTTPS` protocol.
     * 
     */
    public Optional<String> objectUnavailableProtocol() {
        return Optional.ofNullable(this.objectUnavailableProtocol);
    }
    /**
     * @return This sets the recovery option.
     * 
     */
    public Optional<String> objectUnavailableRecovery() {
        return Optional.ofNullable(this.objectUnavailableRecovery);
    }
    /**
     * @return Specifies a redirect response code.
     * 
     */
    public Optional<Integer> objectUnavailableRedirectMethod() {
        return Optional.ofNullable(this.objectUnavailableRedirectMethod);
    }
    /**
     * @return Specifies the set of response codes identifying when there are content errors.
     * 
     */
    public List<String> objectUnavailableResponseCodes() {
        return this.objectUnavailableResponseCodes == null ? List.of() : this.objectUnavailableResponseCodes;
    }
    /**
     * @return Sets how many times to retry.
     * 
     */
    public Optional<String> objectUnavailableRetryLimit() {
        return Optional.ofNullable(this.objectUnavailableRetryLimit);
    }
    /**
     * @return This specifies the redirect&#39;s destination hostname.
     * 
     */
    public Optional<String> originUnavailableAlternateHost() {
        return Optional.ofNullable(this.originUnavailableAlternateHost);
    }
    /**
     * @return This specifies the origin hostname.
     * 
     */
    public Optional<String> originUnavailableBackupHost() {
        return Optional.ofNullable(this.originUnavailableBackupHost);
    }
    /**
     * @return Enabling this blacklists the origin&#39;s IP address.
     * 
     */
    public Optional<Boolean> originUnavailableBlacklistOriginIp() {
        return Optional.ofNullable(this.originUnavailableBlacklistOriginIp);
    }
    /**
     * @return This sets the delay before blacklisting an IP address.
     * 
     */
    public Optional<String> originUnavailableBlacklistWindow() {
        return Optional.ofNullable(this.originUnavailableBlacklistWindow);
    }
    /**
     * @return Modifies the request protocol.
     * 
     */
    public Optional<Boolean> originUnavailableChangeProtocol() {
        return Optional.ofNullable(this.originUnavailableChangeProtocol);
    }
    /**
     * @return Specify `RESPONSE_CODES`, the only available option.
     * 
     */
    public Optional<String> originUnavailableDetectionLevel() {
        return Optional.ofNullable(this.originUnavailableDetectionLevel);
    }
    /**
     * @return Enabling this includes the original set of query parameters.
     * 
     */
    public Optional<Boolean> originUnavailableIncludeQueryString() {
        return Optional.ofNullable(this.originUnavailableIncludeQueryString);
    }
    /**
     * @return This specifies the path to form the new URL.
     * 
     */
    public Optional<String> originUnavailableModifiedPath() {
        return Optional.ofNullable(this.originUnavailableModifiedPath);
    }
    /**
     * @return Modifies the request path.
     * 
     */
    public Optional<Boolean> originUnavailableModifyRequestPath() {
        return Optional.ofNullable(this.originUnavailableModifyRequestPath);
    }
    /**
     * @return Specifies either the `HTTP` or `HTTPS` protocol.
     * 
     */
    public Optional<String> originUnavailableProtocol() {
        return Optional.ofNullable(this.originUnavailableProtocol);
    }
    /**
     * @return This sets the recovery option.
     * 
     */
    public Optional<String> originUnavailableRecovery() {
        return Optional.ofNullable(this.originUnavailableRecovery);
    }
    /**
     * @return Specifies either a redirect response code.
     * 
     */
    public Optional<Integer> originUnavailableRedirectMethod() {
        return Optional.ofNullable(this.originUnavailableRedirectMethod);
    }
    /**
     * @return Specifies the set of response codes identifying when the origin responds with errors.
     * 
     */
    public List<String> originUnavailableResponseCodes() {
        return this.originUnavailableResponseCodes == null ? List.of() : this.originUnavailableResponseCodes;
    }
    /**
     * @return Sets how many times to retry.
     * 
     */
    public Optional<String> originUnavailableRetryLimit() {
        return Optional.ofNullable(this.originUnavailableRetryLimit);
    }
    /**
     * @return This specifies the redirect&#39;s destination hostname.
     * 
     */
    public Optional<String> originUnresponsiveAlternateHost() {
        return Optional.ofNullable(this.originUnresponsiveAlternateHost);
    }
    /**
     * @return This specifies the origin hostname.
     * 
     */
    public Optional<String> originUnresponsiveBackupHost() {
        return Optional.ofNullable(this.originUnresponsiveBackupHost);
    }
    /**
     * @return Enabling this blacklists the origin&#39;s IP address.
     * 
     */
    public Optional<Boolean> originUnresponsiveBlacklistOriginIp() {
        return Optional.ofNullable(this.originUnresponsiveBlacklistOriginIp);
    }
    /**
     * @return This sets the delay before blacklisting an IP address.
     * 
     */
    public Optional<String> originUnresponsiveBlacklistWindow() {
        return Optional.ofNullable(this.originUnresponsiveBlacklistWindow);
    }
    /**
     * @return This allows you to change the request protocol.
     * 
     */
    public Optional<Boolean> originUnresponsiveChangeProtocol() {
        return Optional.ofNullable(this.originUnresponsiveChangeProtocol);
    }
    /**
     * @return Specify the level of response to slow origin connections.
     * 
     */
    public Optional<String> originUnresponsiveDetectionLevel() {
        return Optional.ofNullable(this.originUnresponsiveDetectionLevel);
    }
    /**
     * @return Enabling this includes the original set of query parameters.
     * 
     */
    public Optional<Boolean> originUnresponsiveIncludeQueryString() {
        return Optional.ofNullable(this.originUnresponsiveIncludeQueryString);
    }
    /**
     * @return This specifies the path to form the new URL.
     * 
     */
    public Optional<String> originUnresponsiveModifiedPath() {
        return Optional.ofNullable(this.originUnresponsiveModifiedPath);
    }
    /**
     * @return Modifies the request path.
     * 
     */
    public Optional<Boolean> originUnresponsiveModifyRequestPath() {
        return Optional.ofNullable(this.originUnresponsiveModifyRequestPath);
    }
    /**
     * @return Specifies which protocol to use.
     * 
     */
    public Optional<String> originUnresponsiveProtocol() {
        return Optional.ofNullable(this.originUnresponsiveProtocol);
    }
    /**
     * @return This sets the recovery option.
     * 
     */
    public Optional<String> originUnresponsiveRecovery() {
        return Optional.ofNullable(this.originUnresponsiveRecovery);
    }
    /**
     * @return Specifies the redirect response code.
     * 
     */
    public Optional<Integer> originUnresponsiveRedirectMethod() {
        return Optional.ofNullable(this.originUnresponsiveRedirectMethod);
    }
    /**
     * @return Sets how many times to retry.
     * 
     */
    public Optional<String> originUnresponsiveRetryLimit() {
        return Optional.ofNullable(this.originUnresponsiveRetryLimit);
    }
    /**
     * @return This field is only intended for export compatibility purposes, and modifying it will not impact your use of the behavior.
     * 
     */
    public Optional<String> otherOptions() {
        return Optional.ofNullable(this.otherOptions);
    }
    /**
     * @return This option is for internal usage only.
     * 
     */
    public Optional<String> templateUuid() {
        return Optional.ofNullable(this.templateUuid);
    }
    /**
     * @return A uuid member indicates that at least one of its component behaviors or criteria is advanced and read-only. You need to preserve this uuid as well when modifying the rule tree. This option is for internal usage only.
     * 
     */
    public Optional<String> uuid() {
        return Optional.ofNullable(this.uuid);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPropertyRulesBuilderRulesV20231030BehaviorMediaOriginFailover defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean cacheErrorResponse;
        private @Nullable String cacheWindow;
        private @Nullable String clientResponseCode;
        private @Nullable Boolean detectObjectUnavailable;
        private @Nullable String detectObjectUnavailableTitle;
        private @Nullable Boolean detectOriginUnavailable;
        private @Nullable String detectOriginUnavailableTitle;
        private @Nullable Boolean detectOriginUnresponsive;
        private @Nullable String detectOriginUnresponsiveTitle;
        private @Nullable Boolean locked;
        private @Nullable String objectUnavailableAlternateHost;
        private @Nullable String objectUnavailableBackupHost;
        private @Nullable Boolean objectUnavailableBlacklistOriginIp;
        private @Nullable String objectUnavailableBlacklistWindow;
        private @Nullable Boolean objectUnavailableChangeProtocol;
        private @Nullable String objectUnavailableDetectionLevel;
        private @Nullable Boolean objectUnavailableIncludeQueryString;
        private @Nullable String objectUnavailableModifiedPath;
        private @Nullable Boolean objectUnavailableModifyRequestPath;
        private @Nullable String objectUnavailableProtocol;
        private @Nullable String objectUnavailableRecovery;
        private @Nullable Integer objectUnavailableRedirectMethod;
        private @Nullable List<String> objectUnavailableResponseCodes;
        private @Nullable String objectUnavailableRetryLimit;
        private @Nullable String originUnavailableAlternateHost;
        private @Nullable String originUnavailableBackupHost;
        private @Nullable Boolean originUnavailableBlacklistOriginIp;
        private @Nullable String originUnavailableBlacklistWindow;
        private @Nullable Boolean originUnavailableChangeProtocol;
        private @Nullable String originUnavailableDetectionLevel;
        private @Nullable Boolean originUnavailableIncludeQueryString;
        private @Nullable String originUnavailableModifiedPath;
        private @Nullable Boolean originUnavailableModifyRequestPath;
        private @Nullable String originUnavailableProtocol;
        private @Nullable String originUnavailableRecovery;
        private @Nullable Integer originUnavailableRedirectMethod;
        private @Nullable List<String> originUnavailableResponseCodes;
        private @Nullable String originUnavailableRetryLimit;
        private @Nullable String originUnresponsiveAlternateHost;
        private @Nullable String originUnresponsiveBackupHost;
        private @Nullable Boolean originUnresponsiveBlacklistOriginIp;
        private @Nullable String originUnresponsiveBlacklistWindow;
        private @Nullable Boolean originUnresponsiveChangeProtocol;
        private @Nullable String originUnresponsiveDetectionLevel;
        private @Nullable Boolean originUnresponsiveIncludeQueryString;
        private @Nullable String originUnresponsiveModifiedPath;
        private @Nullable Boolean originUnresponsiveModifyRequestPath;
        private @Nullable String originUnresponsiveProtocol;
        private @Nullable String originUnresponsiveRecovery;
        private @Nullable Integer originUnresponsiveRedirectMethod;
        private @Nullable String originUnresponsiveRetryLimit;
        private @Nullable String otherOptions;
        private @Nullable String templateUuid;
        private @Nullable String uuid;
        public Builder() {}
        public Builder(GetPropertyRulesBuilderRulesV20231030BehaviorMediaOriginFailover defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cacheErrorResponse = defaults.cacheErrorResponse;
    	      this.cacheWindow = defaults.cacheWindow;
    	      this.clientResponseCode = defaults.clientResponseCode;
    	      this.detectObjectUnavailable = defaults.detectObjectUnavailable;
    	      this.detectObjectUnavailableTitle = defaults.detectObjectUnavailableTitle;
    	      this.detectOriginUnavailable = defaults.detectOriginUnavailable;
    	      this.detectOriginUnavailableTitle = defaults.detectOriginUnavailableTitle;
    	      this.detectOriginUnresponsive = defaults.detectOriginUnresponsive;
    	      this.detectOriginUnresponsiveTitle = defaults.detectOriginUnresponsiveTitle;
    	      this.locked = defaults.locked;
    	      this.objectUnavailableAlternateHost = defaults.objectUnavailableAlternateHost;
    	      this.objectUnavailableBackupHost = defaults.objectUnavailableBackupHost;
    	      this.objectUnavailableBlacklistOriginIp = defaults.objectUnavailableBlacklistOriginIp;
    	      this.objectUnavailableBlacklistWindow = defaults.objectUnavailableBlacklistWindow;
    	      this.objectUnavailableChangeProtocol = defaults.objectUnavailableChangeProtocol;
    	      this.objectUnavailableDetectionLevel = defaults.objectUnavailableDetectionLevel;
    	      this.objectUnavailableIncludeQueryString = defaults.objectUnavailableIncludeQueryString;
    	      this.objectUnavailableModifiedPath = defaults.objectUnavailableModifiedPath;
    	      this.objectUnavailableModifyRequestPath = defaults.objectUnavailableModifyRequestPath;
    	      this.objectUnavailableProtocol = defaults.objectUnavailableProtocol;
    	      this.objectUnavailableRecovery = defaults.objectUnavailableRecovery;
    	      this.objectUnavailableRedirectMethod = defaults.objectUnavailableRedirectMethod;
    	      this.objectUnavailableResponseCodes = defaults.objectUnavailableResponseCodes;
    	      this.objectUnavailableRetryLimit = defaults.objectUnavailableRetryLimit;
    	      this.originUnavailableAlternateHost = defaults.originUnavailableAlternateHost;
    	      this.originUnavailableBackupHost = defaults.originUnavailableBackupHost;
    	      this.originUnavailableBlacklistOriginIp = defaults.originUnavailableBlacklistOriginIp;
    	      this.originUnavailableBlacklistWindow = defaults.originUnavailableBlacklistWindow;
    	      this.originUnavailableChangeProtocol = defaults.originUnavailableChangeProtocol;
    	      this.originUnavailableDetectionLevel = defaults.originUnavailableDetectionLevel;
    	      this.originUnavailableIncludeQueryString = defaults.originUnavailableIncludeQueryString;
    	      this.originUnavailableModifiedPath = defaults.originUnavailableModifiedPath;
    	      this.originUnavailableModifyRequestPath = defaults.originUnavailableModifyRequestPath;
    	      this.originUnavailableProtocol = defaults.originUnavailableProtocol;
    	      this.originUnavailableRecovery = defaults.originUnavailableRecovery;
    	      this.originUnavailableRedirectMethod = defaults.originUnavailableRedirectMethod;
    	      this.originUnavailableResponseCodes = defaults.originUnavailableResponseCodes;
    	      this.originUnavailableRetryLimit = defaults.originUnavailableRetryLimit;
    	      this.originUnresponsiveAlternateHost = defaults.originUnresponsiveAlternateHost;
    	      this.originUnresponsiveBackupHost = defaults.originUnresponsiveBackupHost;
    	      this.originUnresponsiveBlacklistOriginIp = defaults.originUnresponsiveBlacklistOriginIp;
    	      this.originUnresponsiveBlacklistWindow = defaults.originUnresponsiveBlacklistWindow;
    	      this.originUnresponsiveChangeProtocol = defaults.originUnresponsiveChangeProtocol;
    	      this.originUnresponsiveDetectionLevel = defaults.originUnresponsiveDetectionLevel;
    	      this.originUnresponsiveIncludeQueryString = defaults.originUnresponsiveIncludeQueryString;
    	      this.originUnresponsiveModifiedPath = defaults.originUnresponsiveModifiedPath;
    	      this.originUnresponsiveModifyRequestPath = defaults.originUnresponsiveModifyRequestPath;
    	      this.originUnresponsiveProtocol = defaults.originUnresponsiveProtocol;
    	      this.originUnresponsiveRecovery = defaults.originUnresponsiveRecovery;
    	      this.originUnresponsiveRedirectMethod = defaults.originUnresponsiveRedirectMethod;
    	      this.originUnresponsiveRetryLimit = defaults.originUnresponsiveRetryLimit;
    	      this.otherOptions = defaults.otherOptions;
    	      this.templateUuid = defaults.templateUuid;
    	      this.uuid = defaults.uuid;
        }

        @CustomType.Setter
        public Builder cacheErrorResponse(@Nullable Boolean cacheErrorResponse) {

            this.cacheErrorResponse = cacheErrorResponse;
            return this;
        }
        @CustomType.Setter
        public Builder cacheWindow(@Nullable String cacheWindow) {

            this.cacheWindow = cacheWindow;
            return this;
        }
        @CustomType.Setter
        public Builder clientResponseCode(@Nullable String clientResponseCode) {

            this.clientResponseCode = clientResponseCode;
            return this;
        }
        @CustomType.Setter
        public Builder detectObjectUnavailable(@Nullable Boolean detectObjectUnavailable) {

            this.detectObjectUnavailable = detectObjectUnavailable;
            return this;
        }
        @CustomType.Setter
        public Builder detectObjectUnavailableTitle(@Nullable String detectObjectUnavailableTitle) {

            this.detectObjectUnavailableTitle = detectObjectUnavailableTitle;
            return this;
        }
        @CustomType.Setter
        public Builder detectOriginUnavailable(@Nullable Boolean detectOriginUnavailable) {

            this.detectOriginUnavailable = detectOriginUnavailable;
            return this;
        }
        @CustomType.Setter
        public Builder detectOriginUnavailableTitle(@Nullable String detectOriginUnavailableTitle) {

            this.detectOriginUnavailableTitle = detectOriginUnavailableTitle;
            return this;
        }
        @CustomType.Setter
        public Builder detectOriginUnresponsive(@Nullable Boolean detectOriginUnresponsive) {

            this.detectOriginUnresponsive = detectOriginUnresponsive;
            return this;
        }
        @CustomType.Setter
        public Builder detectOriginUnresponsiveTitle(@Nullable String detectOriginUnresponsiveTitle) {

            this.detectOriginUnresponsiveTitle = detectOriginUnresponsiveTitle;
            return this;
        }
        @CustomType.Setter
        public Builder locked(@Nullable Boolean locked) {

            this.locked = locked;
            return this;
        }
        @CustomType.Setter
        public Builder objectUnavailableAlternateHost(@Nullable String objectUnavailableAlternateHost) {

            this.objectUnavailableAlternateHost = objectUnavailableAlternateHost;
            return this;
        }
        @CustomType.Setter
        public Builder objectUnavailableBackupHost(@Nullable String objectUnavailableBackupHost) {

            this.objectUnavailableBackupHost = objectUnavailableBackupHost;
            return this;
        }
        @CustomType.Setter
        public Builder objectUnavailableBlacklistOriginIp(@Nullable Boolean objectUnavailableBlacklistOriginIp) {

            this.objectUnavailableBlacklistOriginIp = objectUnavailableBlacklistOriginIp;
            return this;
        }
        @CustomType.Setter
        public Builder objectUnavailableBlacklistWindow(@Nullable String objectUnavailableBlacklistWindow) {

            this.objectUnavailableBlacklistWindow = objectUnavailableBlacklistWindow;
            return this;
        }
        @CustomType.Setter
        public Builder objectUnavailableChangeProtocol(@Nullable Boolean objectUnavailableChangeProtocol) {

            this.objectUnavailableChangeProtocol = objectUnavailableChangeProtocol;
            return this;
        }
        @CustomType.Setter
        public Builder objectUnavailableDetectionLevel(@Nullable String objectUnavailableDetectionLevel) {

            this.objectUnavailableDetectionLevel = objectUnavailableDetectionLevel;
            return this;
        }
        @CustomType.Setter
        public Builder objectUnavailableIncludeQueryString(@Nullable Boolean objectUnavailableIncludeQueryString) {

            this.objectUnavailableIncludeQueryString = objectUnavailableIncludeQueryString;
            return this;
        }
        @CustomType.Setter
        public Builder objectUnavailableModifiedPath(@Nullable String objectUnavailableModifiedPath) {

            this.objectUnavailableModifiedPath = objectUnavailableModifiedPath;
            return this;
        }
        @CustomType.Setter
        public Builder objectUnavailableModifyRequestPath(@Nullable Boolean objectUnavailableModifyRequestPath) {

            this.objectUnavailableModifyRequestPath = objectUnavailableModifyRequestPath;
            return this;
        }
        @CustomType.Setter
        public Builder objectUnavailableProtocol(@Nullable String objectUnavailableProtocol) {

            this.objectUnavailableProtocol = objectUnavailableProtocol;
            return this;
        }
        @CustomType.Setter
        public Builder objectUnavailableRecovery(@Nullable String objectUnavailableRecovery) {

            this.objectUnavailableRecovery = objectUnavailableRecovery;
            return this;
        }
        @CustomType.Setter
        public Builder objectUnavailableRedirectMethod(@Nullable Integer objectUnavailableRedirectMethod) {

            this.objectUnavailableRedirectMethod = objectUnavailableRedirectMethod;
            return this;
        }
        @CustomType.Setter
        public Builder objectUnavailableResponseCodes(@Nullable List<String> objectUnavailableResponseCodes) {

            this.objectUnavailableResponseCodes = objectUnavailableResponseCodes;
            return this;
        }
        public Builder objectUnavailableResponseCodes(String... objectUnavailableResponseCodes) {
            return objectUnavailableResponseCodes(List.of(objectUnavailableResponseCodes));
        }
        @CustomType.Setter
        public Builder objectUnavailableRetryLimit(@Nullable String objectUnavailableRetryLimit) {

            this.objectUnavailableRetryLimit = objectUnavailableRetryLimit;
            return this;
        }
        @CustomType.Setter
        public Builder originUnavailableAlternateHost(@Nullable String originUnavailableAlternateHost) {

            this.originUnavailableAlternateHost = originUnavailableAlternateHost;
            return this;
        }
        @CustomType.Setter
        public Builder originUnavailableBackupHost(@Nullable String originUnavailableBackupHost) {

            this.originUnavailableBackupHost = originUnavailableBackupHost;
            return this;
        }
        @CustomType.Setter
        public Builder originUnavailableBlacklistOriginIp(@Nullable Boolean originUnavailableBlacklistOriginIp) {

            this.originUnavailableBlacklistOriginIp = originUnavailableBlacklistOriginIp;
            return this;
        }
        @CustomType.Setter
        public Builder originUnavailableBlacklistWindow(@Nullable String originUnavailableBlacklistWindow) {

            this.originUnavailableBlacklistWindow = originUnavailableBlacklistWindow;
            return this;
        }
        @CustomType.Setter
        public Builder originUnavailableChangeProtocol(@Nullable Boolean originUnavailableChangeProtocol) {

            this.originUnavailableChangeProtocol = originUnavailableChangeProtocol;
            return this;
        }
        @CustomType.Setter
        public Builder originUnavailableDetectionLevel(@Nullable String originUnavailableDetectionLevel) {

            this.originUnavailableDetectionLevel = originUnavailableDetectionLevel;
            return this;
        }
        @CustomType.Setter
        public Builder originUnavailableIncludeQueryString(@Nullable Boolean originUnavailableIncludeQueryString) {

            this.originUnavailableIncludeQueryString = originUnavailableIncludeQueryString;
            return this;
        }
        @CustomType.Setter
        public Builder originUnavailableModifiedPath(@Nullable String originUnavailableModifiedPath) {

            this.originUnavailableModifiedPath = originUnavailableModifiedPath;
            return this;
        }
        @CustomType.Setter
        public Builder originUnavailableModifyRequestPath(@Nullable Boolean originUnavailableModifyRequestPath) {

            this.originUnavailableModifyRequestPath = originUnavailableModifyRequestPath;
            return this;
        }
        @CustomType.Setter
        public Builder originUnavailableProtocol(@Nullable String originUnavailableProtocol) {

            this.originUnavailableProtocol = originUnavailableProtocol;
            return this;
        }
        @CustomType.Setter
        public Builder originUnavailableRecovery(@Nullable String originUnavailableRecovery) {

            this.originUnavailableRecovery = originUnavailableRecovery;
            return this;
        }
        @CustomType.Setter
        public Builder originUnavailableRedirectMethod(@Nullable Integer originUnavailableRedirectMethod) {

            this.originUnavailableRedirectMethod = originUnavailableRedirectMethod;
            return this;
        }
        @CustomType.Setter
        public Builder originUnavailableResponseCodes(@Nullable List<String> originUnavailableResponseCodes) {

            this.originUnavailableResponseCodes = originUnavailableResponseCodes;
            return this;
        }
        public Builder originUnavailableResponseCodes(String... originUnavailableResponseCodes) {
            return originUnavailableResponseCodes(List.of(originUnavailableResponseCodes));
        }
        @CustomType.Setter
        public Builder originUnavailableRetryLimit(@Nullable String originUnavailableRetryLimit) {

            this.originUnavailableRetryLimit = originUnavailableRetryLimit;
            return this;
        }
        @CustomType.Setter
        public Builder originUnresponsiveAlternateHost(@Nullable String originUnresponsiveAlternateHost) {

            this.originUnresponsiveAlternateHost = originUnresponsiveAlternateHost;
            return this;
        }
        @CustomType.Setter
        public Builder originUnresponsiveBackupHost(@Nullable String originUnresponsiveBackupHost) {

            this.originUnresponsiveBackupHost = originUnresponsiveBackupHost;
            return this;
        }
        @CustomType.Setter
        public Builder originUnresponsiveBlacklistOriginIp(@Nullable Boolean originUnresponsiveBlacklistOriginIp) {

            this.originUnresponsiveBlacklistOriginIp = originUnresponsiveBlacklistOriginIp;
            return this;
        }
        @CustomType.Setter
        public Builder originUnresponsiveBlacklistWindow(@Nullable String originUnresponsiveBlacklistWindow) {

            this.originUnresponsiveBlacklistWindow = originUnresponsiveBlacklistWindow;
            return this;
        }
        @CustomType.Setter
        public Builder originUnresponsiveChangeProtocol(@Nullable Boolean originUnresponsiveChangeProtocol) {

            this.originUnresponsiveChangeProtocol = originUnresponsiveChangeProtocol;
            return this;
        }
        @CustomType.Setter
        public Builder originUnresponsiveDetectionLevel(@Nullable String originUnresponsiveDetectionLevel) {

            this.originUnresponsiveDetectionLevel = originUnresponsiveDetectionLevel;
            return this;
        }
        @CustomType.Setter
        public Builder originUnresponsiveIncludeQueryString(@Nullable Boolean originUnresponsiveIncludeQueryString) {

            this.originUnresponsiveIncludeQueryString = originUnresponsiveIncludeQueryString;
            return this;
        }
        @CustomType.Setter
        public Builder originUnresponsiveModifiedPath(@Nullable String originUnresponsiveModifiedPath) {

            this.originUnresponsiveModifiedPath = originUnresponsiveModifiedPath;
            return this;
        }
        @CustomType.Setter
        public Builder originUnresponsiveModifyRequestPath(@Nullable Boolean originUnresponsiveModifyRequestPath) {

            this.originUnresponsiveModifyRequestPath = originUnresponsiveModifyRequestPath;
            return this;
        }
        @CustomType.Setter
        public Builder originUnresponsiveProtocol(@Nullable String originUnresponsiveProtocol) {

            this.originUnresponsiveProtocol = originUnresponsiveProtocol;
            return this;
        }
        @CustomType.Setter
        public Builder originUnresponsiveRecovery(@Nullable String originUnresponsiveRecovery) {

            this.originUnresponsiveRecovery = originUnresponsiveRecovery;
            return this;
        }
        @CustomType.Setter
        public Builder originUnresponsiveRedirectMethod(@Nullable Integer originUnresponsiveRedirectMethod) {

            this.originUnresponsiveRedirectMethod = originUnresponsiveRedirectMethod;
            return this;
        }
        @CustomType.Setter
        public Builder originUnresponsiveRetryLimit(@Nullable String originUnresponsiveRetryLimit) {

            this.originUnresponsiveRetryLimit = originUnresponsiveRetryLimit;
            return this;
        }
        @CustomType.Setter
        public Builder otherOptions(@Nullable String otherOptions) {

            this.otherOptions = otherOptions;
            return this;
        }
        @CustomType.Setter
        public Builder templateUuid(@Nullable String templateUuid) {

            this.templateUuid = templateUuid;
            return this;
        }
        @CustomType.Setter
        public Builder uuid(@Nullable String uuid) {

            this.uuid = uuid;
            return this;
        }
        public GetPropertyRulesBuilderRulesV20231030BehaviorMediaOriginFailover build() {
            final var _resultValue = new GetPropertyRulesBuilderRulesV20231030BehaviorMediaOriginFailover();
            _resultValue.cacheErrorResponse = cacheErrorResponse;
            _resultValue.cacheWindow = cacheWindow;
            _resultValue.clientResponseCode = clientResponseCode;
            _resultValue.detectObjectUnavailable = detectObjectUnavailable;
            _resultValue.detectObjectUnavailableTitle = detectObjectUnavailableTitle;
            _resultValue.detectOriginUnavailable = detectOriginUnavailable;
            _resultValue.detectOriginUnavailableTitle = detectOriginUnavailableTitle;
            _resultValue.detectOriginUnresponsive = detectOriginUnresponsive;
            _resultValue.detectOriginUnresponsiveTitle = detectOriginUnresponsiveTitle;
            _resultValue.locked = locked;
            _resultValue.objectUnavailableAlternateHost = objectUnavailableAlternateHost;
            _resultValue.objectUnavailableBackupHost = objectUnavailableBackupHost;
            _resultValue.objectUnavailableBlacklistOriginIp = objectUnavailableBlacklistOriginIp;
            _resultValue.objectUnavailableBlacklistWindow = objectUnavailableBlacklistWindow;
            _resultValue.objectUnavailableChangeProtocol = objectUnavailableChangeProtocol;
            _resultValue.objectUnavailableDetectionLevel = objectUnavailableDetectionLevel;
            _resultValue.objectUnavailableIncludeQueryString = objectUnavailableIncludeQueryString;
            _resultValue.objectUnavailableModifiedPath = objectUnavailableModifiedPath;
            _resultValue.objectUnavailableModifyRequestPath = objectUnavailableModifyRequestPath;
            _resultValue.objectUnavailableProtocol = objectUnavailableProtocol;
            _resultValue.objectUnavailableRecovery = objectUnavailableRecovery;
            _resultValue.objectUnavailableRedirectMethod = objectUnavailableRedirectMethod;
            _resultValue.objectUnavailableResponseCodes = objectUnavailableResponseCodes;
            _resultValue.objectUnavailableRetryLimit = objectUnavailableRetryLimit;
            _resultValue.originUnavailableAlternateHost = originUnavailableAlternateHost;
            _resultValue.originUnavailableBackupHost = originUnavailableBackupHost;
            _resultValue.originUnavailableBlacklistOriginIp = originUnavailableBlacklistOriginIp;
            _resultValue.originUnavailableBlacklistWindow = originUnavailableBlacklistWindow;
            _resultValue.originUnavailableChangeProtocol = originUnavailableChangeProtocol;
            _resultValue.originUnavailableDetectionLevel = originUnavailableDetectionLevel;
            _resultValue.originUnavailableIncludeQueryString = originUnavailableIncludeQueryString;
            _resultValue.originUnavailableModifiedPath = originUnavailableModifiedPath;
            _resultValue.originUnavailableModifyRequestPath = originUnavailableModifyRequestPath;
            _resultValue.originUnavailableProtocol = originUnavailableProtocol;
            _resultValue.originUnavailableRecovery = originUnavailableRecovery;
            _resultValue.originUnavailableRedirectMethod = originUnavailableRedirectMethod;
            _resultValue.originUnavailableResponseCodes = originUnavailableResponseCodes;
            _resultValue.originUnavailableRetryLimit = originUnavailableRetryLimit;
            _resultValue.originUnresponsiveAlternateHost = originUnresponsiveAlternateHost;
            _resultValue.originUnresponsiveBackupHost = originUnresponsiveBackupHost;
            _resultValue.originUnresponsiveBlacklistOriginIp = originUnresponsiveBlacklistOriginIp;
            _resultValue.originUnresponsiveBlacklistWindow = originUnresponsiveBlacklistWindow;
            _resultValue.originUnresponsiveChangeProtocol = originUnresponsiveChangeProtocol;
            _resultValue.originUnresponsiveDetectionLevel = originUnresponsiveDetectionLevel;
            _resultValue.originUnresponsiveIncludeQueryString = originUnresponsiveIncludeQueryString;
            _resultValue.originUnresponsiveModifiedPath = originUnresponsiveModifiedPath;
            _resultValue.originUnresponsiveModifyRequestPath = originUnresponsiveModifyRequestPath;
            _resultValue.originUnresponsiveProtocol = originUnresponsiveProtocol;
            _resultValue.originUnresponsiveRecovery = originUnresponsiveRecovery;
            _resultValue.originUnresponsiveRedirectMethod = originUnresponsiveRedirectMethod;
            _resultValue.originUnresponsiveRetryLimit = originUnresponsiveRetryLimit;
            _resultValue.otherOptions = otherOptions;
            _resultValue.templateUuid = templateUuid;
            _resultValue.uuid = uuid;
            return _resultValue;
        }
    }
}
