// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai;

import com.pulumi.akamai.IamApiClientArgs;
import com.pulumi.akamai.Utilities;
import com.pulumi.akamai.inputs.IamApiClientState;
import com.pulumi.akamai.outputs.IamApiClientActions;
import com.pulumi.akamai.outputs.IamApiClientApiAccess;
import com.pulumi.akamai.outputs.IamApiClientCredential;
import com.pulumi.akamai.outputs.IamApiClientGroupAccess;
import com.pulumi.akamai.outputs.IamApiClientIpAcl;
import com.pulumi.akamai.outputs.IamApiClientPurgeOptions;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="akamai:index/iamApiClient:IamApiClient")
public class IamApiClient extends com.pulumi.resources.CustomResource {
    /**
     * The part of the client secret that identifies your API client and lets you access applications and resources.
     * 
     */
    @Export(name="accessToken", refs={String.class}, tree="[0]")
    private Output<String> accessToken;

    /**
     * @return The part of the client secret that identifies your API client and lets you access applications and resources.
     * 
     */
    public Output<String> accessToken() {
        return this.accessToken;
    }
    /**
     * Specifies activities available for the API client.
     * 
     */
    @Export(name="actions", refs={IamApiClientActions.class}, tree="[0]")
    private Output<IamApiClientActions> actions;

    /**
     * @return Specifies activities available for the API client.
     * 
     */
    public Output<IamApiClientActions> actions() {
        return this.actions;
    }
    /**
     * The number of credentials active for the API client. When the count is zero, you can delete the API client without interruption.
     * 
     */
    @Export(name="activeCredentialCount", refs={Integer.class}, tree="[0]")
    private Output<Integer> activeCredentialCount;

    /**
     * @return The number of credentials active for the API client. When the count is zero, you can delete the API client without interruption.
     * 
     */
    public Output<Integer> activeCredentialCount() {
        return this.activeCredentialCount;
    }
    /**
     * Enables the API client to manage more than one account.
     * 
     */
    @Export(name="allowAccountSwitch", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> allowAccountSwitch;

    /**
     * @return Enables the API client to manage more than one account.
     * 
     */
    public Output<Boolean> allowAccountSwitch() {
        return this.allowAccountSwitch;
    }
    /**
     * The APIs the API client can access.
     * 
     */
    @Export(name="apiAccess", refs={IamApiClientApiAccess.class}, tree="[0]")
    private Output<IamApiClientApiAccess> apiAccess;

    /**
     * @return The APIs the API client can access.
     * 
     */
    public Output<IamApiClientApiAccess> apiAccess() {
        return this.apiAccess;
    }
    /**
     * The API client&#39;s valid users. When the &#39;client_type&#39; is either &#39;CLIENT&#39; or &#39;USER_CLIENT&#39;, you need to specify a single username in an array.
     * 
     */
    @Export(name="authorizedUsers", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> authorizedUsers;

    /**
     * @return The API client&#39;s valid users. When the &#39;client_type&#39; is either &#39;CLIENT&#39; or &#39;USER_CLIENT&#39;, you need to specify a single username in an array.
     * 
     */
    public Output<List<String>> authorizedUsers() {
        return this.authorizedUsers;
    }
    /**
     * The base URL for the service.
     * 
     */
    @Export(name="baseUrl", refs={String.class}, tree="[0]")
    private Output<String> baseUrl;

    /**
     * @return The base URL for the service.
     * 
     */
    public Output<String> baseUrl() {
        return this.baseUrl;
    }
    /**
     * Whether the API client can create a credential for a new API client. The default is false.
     * 
     */
    @Export(name="canAutoCreateCredential", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> canAutoCreateCredential;

    /**
     * @return Whether the API client can create a credential for a new API client. The default is false.
     * 
     */
    public Output<Boolean> canAutoCreateCredential() {
        return this.canAutoCreateCredential;
    }
    /**
     * A human-readable description of the API client.
     * 
     */
    @Export(name="clientDescription", refs={String.class}, tree="[0]")
    private Output<String> clientDescription;

    /**
     * @return A human-readable description of the API client.
     * 
     */
    public Output<String> clientDescription() {
        return this.clientDescription;
    }
    /**
     * A unique identifier for the API client.
     * 
     */
    @Export(name="clientId", refs={String.class}, tree="[0]")
    private Output<String> clientId;

    /**
     * @return A unique identifier for the API client.
     * 
     */
    public Output<String> clientId() {
        return this.clientId;
    }
    /**
     * A human-readable name for the API client.
     * 
     */
    @Export(name="clientName", refs={String.class}, tree="[0]")
    private Output<String> clientName;

    /**
     * @return A human-readable name for the API client.
     * 
     */
    public Output<String> clientName() {
        return this.clientName;
    }
    /**
     * Specifies the API client&#39;s ownership and credential management. &#39;CLIENT&#39; indicates the creator owns and manages the credentials. &#39;USER_CLIENT&#39; indicates another user owns the client and manages the credentials.
     * 
     */
    @Export(name="clientType", refs={String.class}, tree="[0]")
    private Output<String> clientType;

    /**
     * @return Specifies the API client&#39;s ownership and credential management. &#39;CLIENT&#39; indicates the creator owns and manages the credentials. &#39;USER_CLIENT&#39; indicates another user owns the client and manages the credentials.
     * 
     */
    public Output<String> clientType() {
        return this.clientType;
    }
    /**
     * The user who created the API client.
     * 
     */
    @Export(name="createdBy", refs={String.class}, tree="[0]")
    private Output<String> createdBy;

    /**
     * @return The user who created the API client.
     * 
     */
    public Output<String> createdBy() {
        return this.createdBy;
    }
    /**
     * The ISO 8601 timestamp indicating when the API client was created.
     * 
     */
    @Export(name="createdDate", refs={String.class}, tree="[0]")
    private Output<String> createdDate;

    /**
     * @return The ISO 8601 timestamp indicating when the API client was created.
     * 
     */
    public Output<String> createdDate() {
        return this.createdDate;
    }
    @Export(name="credential", refs={IamApiClientCredential.class}, tree="[0]")
    private Output<IamApiClientCredential> credential;

    public Output<IamApiClientCredential> credential() {
        return this.credential;
    }
    /**
     * Specifies the API client&#39;s group access.
     * 
     */
    @Export(name="groupAccess", refs={IamApiClientGroupAccess.class}, tree="[0]")
    private Output<IamApiClientGroupAccess> groupAccess;

    /**
     * @return Specifies the API client&#39;s group access.
     * 
     */
    public Output<IamApiClientGroupAccess> groupAccess() {
        return this.groupAccess;
    }
    /**
     * Specifies the API client&#39;s IP list restriction.
     * 
     */
    @Export(name="ipAcl", refs={IamApiClientIpAcl.class}, tree="[0]")
    private Output</* @Nullable */ IamApiClientIpAcl> ipAcl;

    /**
     * @return Specifies the API client&#39;s IP list restriction.
     * 
     */
    public Output<Optional<IamApiClientIpAcl>> ipAcl() {
        return Codegen.optional(this.ipAcl);
    }
    /**
     * Whether to lock or unlock the API client.
     * 
     */
    @Export(name="lock", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> lock;

    /**
     * @return Whether to lock or unlock the API client.
     * 
     */
    public Output<Boolean> lock() {
        return this.lock;
    }
    /**
     * Email addresses to notify users when credentials expire.
     * 
     */
    @Export(name="notificationEmails", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> notificationEmails;

    /**
     * @return Email addresses to notify users when credentials expire.
     * 
     */
    public Output<List<String>> notificationEmails() {
        return this.notificationEmails;
    }
    /**
     * Configures the API client to access the Fast Purge API. Provide it only if the `apis` attribute includes an `api_name` of `CCU API`.
     * 
     */
    @Export(name="purgeOptions", refs={IamApiClientPurgeOptions.class}, tree="[0]")
    private Output</* @Nullable */ IamApiClientPurgeOptions> purgeOptions;

    /**
     * @return Configures the API client to access the Fast Purge API. Provide it only if the `apis` attribute includes an `api_name` of `CCU API`.
     * 
     */
    public Output<Optional<IamApiClientPurgeOptions>> purgeOptions() {
        return Codegen.optional(this.purgeOptions);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public IamApiClient(java.lang.String name) {
        this(name, IamApiClientArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public IamApiClient(java.lang.String name, IamApiClientArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public IamApiClient(java.lang.String name, IamApiClientArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("akamai:index/iamApiClient:IamApiClient", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private IamApiClient(java.lang.String name, Output<java.lang.String> id, @Nullable IamApiClientState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("akamai:index/iamApiClient:IamApiClient", name, state, makeResourceOptions(options, id), false);
    }

    private static IamApiClientArgs makeArgs(IamApiClientArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? IamApiClientArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "accessToken",
                "baseUrl"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static IamApiClient get(java.lang.String name, Output<java.lang.String> id, @Nullable IamApiClientState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new IamApiClient(name, id, state, options);
    }
}
