// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NetworkListActivationsArgs extends com.pulumi.resources.ResourceArgs {

    public static final NetworkListActivationsArgs Empty = new NetworkListActivationsArgs();

    /**
     * @deprecated
     * The setting &#34;activate&#34; has been deprecated.
     * 
     */
    @Deprecated /* The setting ""activate"" has been deprecated. */
    @Import(name="activate")
    private @Nullable Output<Boolean> activate;

    /**
     * @deprecated
     * The setting &#34;activate&#34; has been deprecated.
     * 
     */
    @Deprecated /* The setting ""activate"" has been deprecated. */
    public Optional<Output<Boolean>> activate() {
        return Optional.ofNullable(this.activate);
    }

    /**
     * The network to be used, either `STAGING` or `PRODUCTION`. If not supplied, defaults to
     * `STAGING`.
     * 
     */
    @Import(name="network")
    private @Nullable Output<String> network;

    /**
     * @return The network to be used, either `STAGING` or `PRODUCTION`. If not supplied, defaults to
     * `STAGING`.
     * 
     */
    public Optional<Output<String>> network() {
        return Optional.ofNullable(this.network);
    }

    /**
     * The ID of the network list to be activated
     * 
     */
    @Import(name="networkListId", required=true)
    private Output<String> networkListId;

    /**
     * @return The ID of the network list to be activated
     * 
     */
    public Output<String> networkListId() {
        return this.networkListId;
    }

    /**
     * A comment describing the activation.
     * 
     */
    @Import(name="notes")
    private @Nullable Output<String> notes;

    /**
     * @return A comment describing the activation.
     * 
     */
    public Optional<Output<String>> notes() {
        return Optional.ofNullable(this.notes);
    }

    /**
     * A bracketed, comma-separated list of email addresses that will be notified when the
     * operation is complete.
     * 
     */
    @Import(name="notificationEmails", required=true)
    private Output<List<String>> notificationEmails;

    /**
     * @return A bracketed, comma-separated list of email addresses that will be notified when the
     * operation is complete.
     * 
     */
    public Output<List<String>> notificationEmails() {
        return this.notificationEmails;
    }

    private NetworkListActivationsArgs() {}

    private NetworkListActivationsArgs(NetworkListActivationsArgs $) {
        this.activate = $.activate;
        this.network = $.network;
        this.networkListId = $.networkListId;
        this.notes = $.notes;
        this.notificationEmails = $.notificationEmails;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NetworkListActivationsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NetworkListActivationsArgs $;

        public Builder() {
            $ = new NetworkListActivationsArgs();
        }

        public Builder(NetworkListActivationsArgs defaults) {
            $ = new NetworkListActivationsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @return builder
         * 
         * @deprecated
         * The setting &#34;activate&#34; has been deprecated.
         * 
         */
        @Deprecated /* The setting ""activate"" has been deprecated. */
        public Builder activate(@Nullable Output<Boolean> activate) {
            $.activate = activate;
            return this;
        }

        /**
         * @return builder
         * 
         * @deprecated
         * The setting &#34;activate&#34; has been deprecated.
         * 
         */
        @Deprecated /* The setting ""activate"" has been deprecated. */
        public Builder activate(Boolean activate) {
            return activate(Output.of(activate));
        }

        /**
         * @param network The network to be used, either `STAGING` or `PRODUCTION`. If not supplied, defaults to
         * `STAGING`.
         * 
         * @return builder
         * 
         */
        public Builder network(@Nullable Output<String> network) {
            $.network = network;
            return this;
        }

        /**
         * @param network The network to be used, either `STAGING` or `PRODUCTION`. If not supplied, defaults to
         * `STAGING`.
         * 
         * @return builder
         * 
         */
        public Builder network(String network) {
            return network(Output.of(network));
        }

        /**
         * @param networkListId The ID of the network list to be activated
         * 
         * @return builder
         * 
         */
        public Builder networkListId(Output<String> networkListId) {
            $.networkListId = networkListId;
            return this;
        }

        /**
         * @param networkListId The ID of the network list to be activated
         * 
         * @return builder
         * 
         */
        public Builder networkListId(String networkListId) {
            return networkListId(Output.of(networkListId));
        }

        /**
         * @param notes A comment describing the activation.
         * 
         * @return builder
         * 
         */
        public Builder notes(@Nullable Output<String> notes) {
            $.notes = notes;
            return this;
        }

        /**
         * @param notes A comment describing the activation.
         * 
         * @return builder
         * 
         */
        public Builder notes(String notes) {
            return notes(Output.of(notes));
        }

        /**
         * @param notificationEmails A bracketed, comma-separated list of email addresses that will be notified when the
         * operation is complete.
         * 
         * @return builder
         * 
         */
        public Builder notificationEmails(Output<List<String>> notificationEmails) {
            $.notificationEmails = notificationEmails;
            return this;
        }

        /**
         * @param notificationEmails A bracketed, comma-separated list of email addresses that will be notified when the
         * operation is complete.
         * 
         * @return builder
         * 
         */
        public Builder notificationEmails(List<String> notificationEmails) {
            return notificationEmails(Output.of(notificationEmails));
        }

        /**
         * @param notificationEmails A bracketed, comma-separated list of email addresses that will be notified when the
         * operation is complete.
         * 
         * @return builder
         * 
         */
        public Builder notificationEmails(String... notificationEmails) {
            return notificationEmails(List.of(notificationEmails));
        }

        public NetworkListActivationsArgs build() {
            $.networkListId = Objects.requireNonNull($.networkListId, "expected parameter 'networkListId' to be non-null");
            $.notificationEmails = Objects.requireNonNull($.notificationEmails, "expected parameter 'notificationEmails' to be non-null");
            return $;
        }
    }

}
