// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package akamai

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-akamai/sdk/v11/go/akamai/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupAppsecUrlProtectionPolicy(ctx *pulumi.Context, args *LookupAppsecUrlProtectionPolicyArgs, opts ...pulumi.InvokeOption) (*LookupAppsecUrlProtectionPolicyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAppsecUrlProtectionPolicyResult
	err := ctx.Invoke("akamai:index/getAppsecUrlProtectionPolicy:getAppsecUrlProtectionPolicy", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAppsecUrlProtectionPolicy.
type LookupAppsecUrlProtectionPolicyArgs struct {
	ConfigId              int `pulumi:"configId"`
	UrlProtectionPolicyId int `pulumi:"urlProtectionPolicyId"`
}

// A collection of values returned by getAppsecUrlProtectionPolicy.
type LookupAppsecUrlProtectionPolicyResult struct {
	ApiDefinitions   []GetAppsecUrlProtectionPolicyApiDefinition   `pulumi:"apiDefinitions"`
	BypassConditions []GetAppsecUrlProtectionPolicyBypassCondition `pulumi:"bypassConditions"`
	ConfigId         int                                           `pulumi:"configId"`
	CreateDate       string                                        `pulumi:"createDate"`
	CreatedBy        string                                        `pulumi:"createdBy"`
	Description      string                                        `pulumi:"description"`
	HostnamePaths    []GetAppsecUrlProtectionPolicyHostnamePath    `pulumi:"hostnamePaths"`
	// The provider-assigned unique ID for this managed resource.
	Id                      string                                              `pulumi:"id"`
	IntelligentLoadShedding GetAppsecUrlProtectionPolicyIntelligentLoadShedding `pulumi:"intelligentLoadShedding"`
	MaxRateThreshold        int                                                 `pulumi:"maxRateThreshold"`
	Name                    string                                              `pulumi:"name"`
	UpdateDate              string                                              `pulumi:"updateDate"`
	UpdatedBy               string                                              `pulumi:"updatedBy"`
	UrlProtectionPolicyId   int                                                 `pulumi:"urlProtectionPolicyId"`
	Used                    bool                                                `pulumi:"used"`
}

func LookupAppsecUrlProtectionPolicyOutput(ctx *pulumi.Context, args LookupAppsecUrlProtectionPolicyOutputArgs, opts ...pulumi.InvokeOption) LookupAppsecUrlProtectionPolicyResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupAppsecUrlProtectionPolicyResultOutput, error) {
			args := v.(LookupAppsecUrlProtectionPolicyArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("akamai:index/getAppsecUrlProtectionPolicy:getAppsecUrlProtectionPolicy", args, LookupAppsecUrlProtectionPolicyResultOutput{}, options).(LookupAppsecUrlProtectionPolicyResultOutput), nil
		}).(LookupAppsecUrlProtectionPolicyResultOutput)
}

// A collection of arguments for invoking getAppsecUrlProtectionPolicy.
type LookupAppsecUrlProtectionPolicyOutputArgs struct {
	ConfigId              pulumi.IntInput `pulumi:"configId"`
	UrlProtectionPolicyId pulumi.IntInput `pulumi:"urlProtectionPolicyId"`
}

func (LookupAppsecUrlProtectionPolicyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAppsecUrlProtectionPolicyArgs)(nil)).Elem()
}

// A collection of values returned by getAppsecUrlProtectionPolicy.
type LookupAppsecUrlProtectionPolicyResultOutput struct{ *pulumi.OutputState }

func (LookupAppsecUrlProtectionPolicyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAppsecUrlProtectionPolicyResult)(nil)).Elem()
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) ToLookupAppsecUrlProtectionPolicyResultOutput() LookupAppsecUrlProtectionPolicyResultOutput {
	return o
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) ToLookupAppsecUrlProtectionPolicyResultOutputWithContext(ctx context.Context) LookupAppsecUrlProtectionPolicyResultOutput {
	return o
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) ApiDefinitions() GetAppsecUrlProtectionPolicyApiDefinitionArrayOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) []GetAppsecUrlProtectionPolicyApiDefinition {
		return v.ApiDefinitions
	}).(GetAppsecUrlProtectionPolicyApiDefinitionArrayOutput)
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) BypassConditions() GetAppsecUrlProtectionPolicyBypassConditionArrayOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) []GetAppsecUrlProtectionPolicyBypassCondition {
		return v.BypassConditions
	}).(GetAppsecUrlProtectionPolicyBypassConditionArrayOutput)
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) ConfigId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) int { return v.ConfigId }).(pulumi.IntOutput)
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) CreateDate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) string { return v.CreateDate }).(pulumi.StringOutput)
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) CreatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) string { return v.CreatedBy }).(pulumi.StringOutput)
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) HostnamePaths() GetAppsecUrlProtectionPolicyHostnamePathArrayOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) []GetAppsecUrlProtectionPolicyHostnamePath {
		return v.HostnamePaths
	}).(GetAppsecUrlProtectionPolicyHostnamePathArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupAppsecUrlProtectionPolicyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) IntelligentLoadShedding() GetAppsecUrlProtectionPolicyIntelligentLoadSheddingOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) GetAppsecUrlProtectionPolicyIntelligentLoadShedding {
		return v.IntelligentLoadShedding
	}).(GetAppsecUrlProtectionPolicyIntelligentLoadSheddingOutput)
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) MaxRateThreshold() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) int { return v.MaxRateThreshold }).(pulumi.IntOutput)
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) UpdateDate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) string { return v.UpdateDate }).(pulumi.StringOutput)
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) UpdatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) string { return v.UpdatedBy }).(pulumi.StringOutput)
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) UrlProtectionPolicyId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) int { return v.UrlProtectionPolicyId }).(pulumi.IntOutput)
}

func (o LookupAppsecUrlProtectionPolicyResultOutput) Used() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAppsecUrlProtectionPolicyResult) bool { return v.Used }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAppsecUrlProtectionPolicyResultOutput{})
}
