// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Outputs
{

    [OutputType]
    public sealed class CloudcertificatesActivationProduction
    {
        /// <summary>
        /// The time the activation request was created.
        /// </summary>
        public readonly string? ActivationCreatedTime;
        /// <summary>
        /// Unique identifier of the activation request.
        /// </summary>
        public readonly int? ActivationId;
        /// <summary>
        /// The time the activation request was last modified.
        /// </summary>
        public readonly string? ActivationModifiedTime;
        /// <summary>
        /// The status of the activation request: `INIT`, `PENDING`, `IN_PROGRESS`, `COMPLETE`, `PARTIAL_SUCCESS`, `FAILED`, or `ABORTED`.
        /// </summary>
        public readonly string? ActivationStatus;
        /// <summary>
        /// The type of the activation operation. Always `PROMOTE` for this resource.
        /// </summary>
        public readonly string? ActivationType;
        /// <summary>
        /// The user who created the activation request.
        /// </summary>
        public readonly string? CreatedBy;
        /// <summary>
        /// Error type information when the activation failed, or null otherwise.
        /// </summary>
        public readonly string? ErrorTypes;
        /// <summary>
        /// Unique identifier of the generation actually tracked as active on the PRODUCTION network.
        /// </summary>
        public readonly int? GenerationId;
        /// <summary>
        /// The number of hostnames still in progress for this activation, or null if not yet known.
        /// </summary>
        public readonly int? InProgressHostnameCount;
        /// <summary>
        /// The user who last modified the activation request.
        /// </summary>
        public readonly string? ModifiedBy;
        /// <summary>
        /// The activation request that pre-empted (superseded) this one, or null if this activation was not pre-empted.
        /// </summary>
        public readonly int? PreEmptedBy;
        /// <summary>
        /// The total number of hostnames being deployed as part of this activation, or null if not yet known.
        /// </summary>
        public readonly int? TotalHostnameCount;

        [OutputConstructor]
        private CloudcertificatesActivationProduction(
            string? activationCreatedTime,

            int? activationId,

            string? activationModifiedTime,

            string? activationStatus,

            string? activationType,

            string? createdBy,

            string? errorTypes,

            int? generationId,

            int? inProgressHostnameCount,

            string? modifiedBy,

            int? preEmptedBy,

            int? totalHostnameCount)
        {
            ActivationCreatedTime = activationCreatedTime;
            ActivationId = activationId;
            ActivationModifiedTime = activationModifiedTime;
            ActivationStatus = activationStatus;
            ActivationType = activationType;
            CreatedBy = createdBy;
            ErrorTypes = errorTypes;
            GenerationId = generationId;
            InProgressHostnameCount = inProgressHostnameCount;
            ModifiedBy = modifiedBy;
            PreEmptedBy = preEmptedBy;
            TotalHostnameCount = totalHostnameCount;
        }
    }
}
