// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Outputs
{

    [OutputType]
    public sealed class GetDatastreamDatasetFieldsFieldDatasetFieldResult
    {
        public readonly string DatasetFieldDescription;
        public readonly int DatasetFieldId;
        public readonly string DatasetFieldJsonKey;
        public readonly string DatasetFieldName;

        [OutputConstructor]
        private GetDatastreamDatasetFieldsFieldDatasetFieldResult(
            string datasetFieldDescription,

            int datasetFieldId,

            string datasetFieldJsonKey,

            string datasetFieldName)
        {
            DatasetFieldDescription = datasetFieldDescription;
            DatasetFieldId = datasetFieldId;
            DatasetFieldJsonKey = datasetFieldJsonKey;
            DatasetFieldName = datasetFieldName;
        }
    }
}
