// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Outputs
{

    [OutputType]
    public sealed class GetGroupsGroupResult
    {
        public readonly ImmutableArray<string> ContractIds;
        public readonly string GroupId;
        public readonly string GroupName;
        public readonly string ParentGroupId;

        [OutputConstructor]
        private GetGroupsGroupResult(
            ImmutableArray<string> contractIds,

            string groupId,

            string groupName,

            string parentGroupId)
        {
            ContractIds = contractIds;
            GroupId = groupId;
            GroupName = groupName;
            ParentGroupId = parentGroupId;
        }
    }
}
