// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Outputs
{

    [OutputType]
    public sealed class GetImagingPolicyImagePolicyTransformationIfDimensionLessThanCompoundTransformationIfOrientationResult
    {
        public readonly Outputs.GetImagingPolicyImagePolicyTransformationIfDimensionLessThanCompoundTransformationIfOrientationDefaultResult? Default;
        public readonly Outputs.GetImagingPolicyImagePolicyTransformationIfDimensionLessThanCompoundTransformationIfOrientationLandscapeResult? Landscape;
        public readonly Outputs.GetImagingPolicyImagePolicyTransformationIfDimensionLessThanCompoundTransformationIfOrientationPortraitResult? Portrait;
        public readonly Outputs.GetImagingPolicyImagePolicyTransformationIfDimensionLessThanCompoundTransformationIfOrientationSquareResult? Square;

        [OutputConstructor]
        private GetImagingPolicyImagePolicyTransformationIfDimensionLessThanCompoundTransformationIfOrientationResult(
            Outputs.GetImagingPolicyImagePolicyTransformationIfDimensionLessThanCompoundTransformationIfOrientationDefaultResult? @default,

            Outputs.GetImagingPolicyImagePolicyTransformationIfDimensionLessThanCompoundTransformationIfOrientationLandscapeResult? landscape,

            Outputs.GetImagingPolicyImagePolicyTransformationIfDimensionLessThanCompoundTransformationIfOrientationPortraitResult? portrait,

            Outputs.GetImagingPolicyImagePolicyTransformationIfDimensionLessThanCompoundTransformationIfOrientationSquareResult? square)
        {
            Default = @default;
            Landscape = landscape;
            Portrait = portrait;
            Square = square;
        }
    }
}
