// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;


public final class GetBotmanCustomCodePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetBotmanCustomCodePlainArgs Empty = new GetBotmanCustomCodePlainArgs();

    @Import(name="configId", required=true)
    private Integer configId;

    public Integer configId() {
        return this.configId;
    }

    private GetBotmanCustomCodePlainArgs() {}

    private GetBotmanCustomCodePlainArgs(GetBotmanCustomCodePlainArgs $) {
        this.configId = $.configId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetBotmanCustomCodePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetBotmanCustomCodePlainArgs $;

        public Builder() {
            $ = new GetBotmanCustomCodePlainArgs();
        }

        public Builder(GetBotmanCustomCodePlainArgs defaults) {
            $ = new GetBotmanCustomCodePlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder configId(Integer configId) {
            $.configId = configId;
            return this;
        }

        public GetBotmanCustomCodePlainArgs build() {
            if ($.configId == null) {
                throw new MissingRequiredPropertyException("GetBotmanCustomCodePlainArgs", "configId");
            }
            return $;
        }
    }

}
