// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;

import com.pulumi.akamai.inputs.GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShapePoint;
import com.pulumi.core.annotations.Import;
import java.util.List;
import java.util.Objects;


public final class GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShape extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShape Empty = new GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShape();

    @Import(name="points", required=true)
    private List<GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShapePoint> points;

    public List<GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShapePoint> points() {
        return this.points;
    }

    private GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShape() {}

    private GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShape(GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShape $) {
        this.points = $.points;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShape defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShape $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShape();
        }

        public Builder(GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShape defaults) {
            $ = new GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShape(Objects.requireNonNull(defaults));
        }

        public Builder points(List<GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShapePoint> points) {
            $.points = points;
            return this;
        }

        public Builder points(GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShapePoint... points) {
            return points(List.of(points));
        }

        public GetImagingPolicyImagePolicyTransformationIfOrientationPortraitRegionOfInterestCropRegionOfInterestPolygonShape build() {
            $.points = Objects.requireNonNull($.points, "expected parameter 'points' to be non-null");
            return $;
        }
    }

}
