// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;

import com.pulumi.akamai.inputs.GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompoundTransformation;
import com.pulumi.core.annotations.Import;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompound extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompound Empty = new GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompound();

    @Import(name="transformations")
    private @Nullable List<GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompoundTransformation> transformations;

    public Optional<List<GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompoundTransformation>> transformations() {
        return Optional.ofNullable(this.transformations);
    }

    private GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompound() {}

    private GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompound(GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompound $) {
        this.transformations = $.transformations;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompound defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompound $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompound();
        }

        public Builder(GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompound defaults) {
            $ = new GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompound(Objects.requireNonNull(defaults));
        }

        public Builder transformations(@Nullable List<GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompoundTransformation> transformations) {
            $.transformations = transformations;
            return this;
        }

        public Builder transformations(GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompoundTransformation... transformations) {
            return transformations(List.of(transformations));
        }

        public GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfOrientationDefaultCompound build() {
            return $;
        }
    }

}
