// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanCompositeImageUrlImageTransformationArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanCompositeImageUrlImageTransformationArgs Empty = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanCompositeImageUrlImageTransformationArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanCompositeImageUrlImageTransformationArgs $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanCompositeImageUrlImageTransformationArgs();
        }
        public GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanCompositeImageUrlImageTransformationArgs build() {
            return $;
        }
    }

}
