// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyTransformationIfDimensionLessThanAppendImageTextImageTransformation extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyTransformationIfDimensionLessThanAppendImageTextImageTransformation Empty = new GetImagingPolicyImagePolicyTransformationIfDimensionLessThanAppendImageTextImageTransformation();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationIfDimensionLessThanAppendImageTextImageTransformation $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationIfDimensionLessThanAppendImageTextImageTransformation();
        }
        public GetImagingPolicyImagePolicyTransformationIfDimensionLessThanAppendImageTextImageTransformation build() {
            return $;
        }
    }

}
