// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanIfOrientationLandscapeCompositeImageArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanIfOrientationLandscapeCompositeImageArgs Empty = new GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanIfOrientationLandscapeCompositeImageArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanIfOrientationLandscapeCompositeImageArgs $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanIfOrientationLandscapeCompositeImageArgs();
        }
        public GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanIfOrientationLandscapeCompositeImageArgs build() {
            return $;
        }
    }

}
