// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class GetImagingPolicyImagePolicyTransformationFitAndFillFillTransformationImQueryArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetImagingPolicyImagePolicyTransformationFitAndFillFillTransformationImQueryArgs Empty = new GetImagingPolicyImagePolicyTransformationFitAndFillFillTransformationImQueryArgs();

    @Import(name="allowedTransformations", required=true)
    private Output<List<String>> allowedTransformations;

    public Output<List<String>> allowedTransformations() {
        return this.allowedTransformations;
    }

    @Import(name="queryVar", required=true)
    private Output<String> queryVar;

    public Output<String> queryVar() {
        return this.queryVar;
    }

    private GetImagingPolicyImagePolicyTransformationFitAndFillFillTransformationImQueryArgs() {}

    private GetImagingPolicyImagePolicyTransformationFitAndFillFillTransformationImQueryArgs(GetImagingPolicyImagePolicyTransformationFitAndFillFillTransformationImQueryArgs $) {
        this.allowedTransformations = $.allowedTransformations;
        this.queryVar = $.queryVar;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetImagingPolicyImagePolicyTransformationFitAndFillFillTransformationImQueryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationFitAndFillFillTransformationImQueryArgs $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationFitAndFillFillTransformationImQueryArgs();
        }

        public Builder(GetImagingPolicyImagePolicyTransformationFitAndFillFillTransformationImQueryArgs defaults) {
            $ = new GetImagingPolicyImagePolicyTransformationFitAndFillFillTransformationImQueryArgs(Objects.requireNonNull(defaults));
        }

        public Builder allowedTransformations(Output<List<String>> allowedTransformations) {
            $.allowedTransformations = allowedTransformations;
            return this;
        }

        public Builder allowedTransformations(List<String> allowedTransformations) {
            return allowedTransformations(Output.of(allowedTransformations));
        }

        public Builder allowedTransformations(String... allowedTransformations) {
            return allowedTransformations(List.of(allowedTransformations));
        }

        public Builder queryVar(Output<String> queryVar) {
            $.queryVar = queryVar;
            return this;
        }

        public Builder queryVar(String queryVar) {
            return queryVar(Output.of(queryVar));
        }

        public GetImagingPolicyImagePolicyTransformationFitAndFillFillTransformationImQueryArgs build() {
            $.allowedTransformations = Objects.requireNonNull($.allowedTransformations, "expected parameter 'allowedTransformations' to be non-null");
            $.queryVar = Objects.requireNonNull($.queryVar, "expected parameter 'queryVar' to be non-null");
            return $;
        }
    }

}
