// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfOrientationSquareIfOrientationDefault extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfOrientationSquareIfOrientationDefault Empty = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfOrientationSquareIfOrientationDefault();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfOrientationSquareIfOrientationDefault $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfOrientationSquareIfOrientationDefault();
        }
        public GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfOrientationSquareIfOrientationDefault build() {
            return $;
        }
    }

}
