// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyTransformationIfDimensionDefaultFitAndFillFillTransformationAppendImage extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyTransformationIfDimensionDefaultFitAndFillFillTransformationAppendImage Empty = new GetImagingPolicyImagePolicyTransformationIfDimensionDefaultFitAndFillFillTransformationAppendImage();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationIfDimensionDefaultFitAndFillFillTransformationAppendImage $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationIfDimensionDefaultFitAndFillFillTransformationAppendImage();
        }
        public GetImagingPolicyImagePolicyTransformationIfDimensionDefaultFitAndFillFillTransformationAppendImage build() {
            return $;
        }
    }

}
