// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionEqualIfOrientationLandscapeIfDimensionDefaultArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionEqualIfOrientationLandscapeIfDimensionDefaultArgs Empty = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionEqualIfOrientationLandscapeIfDimensionDefaultArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionEqualIfOrientationLandscapeIfDimensionDefaultArgs $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionEqualIfOrientationLandscapeIfDimensionDefaultArgs();
        }
        public GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionEqualIfOrientationLandscapeIfDimensionDefaultArgs build() {
            return $;
        }
    }

}
