// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanFitAndFillFillTransformationIfDimensionDefault extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanFitAndFillFillTransformationIfDimensionDefault Empty = new GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanFitAndFillFillTransformationIfDimensionDefault();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanFitAndFillFillTransformationIfDimensionDefault $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanFitAndFillFillTransformationIfDimensionDefault();
        }
        public GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanFitAndFillFillTransformationIfDimensionDefault build() {
            return $;
        }
    }

}
