// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualCompositeImage extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualCompositeImage Empty = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualCompositeImage();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualCompositeImage $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualCompositeImage();
        }
        public GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualCompositeImage build() {
            return $;
        }
    }

}
