// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionDefaultIfOrientationLandscapeIfDimensionEqual extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionDefaultIfOrientationLandscapeIfDimensionEqual Empty = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionDefaultIfOrientationLandscapeIfDimensionEqual();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionDefaultIfOrientationLandscapeIfDimensionEqual $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionDefaultIfOrientationLandscapeIfDimensionEqual();
        }
        public GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionDefaultIfOrientationLandscapeIfDimensionEqual build() {
            return $;
        }
    }

}
