// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanIfDimensionGreaterThanIfDimensionLessThan extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanIfDimensionGreaterThanIfDimensionLessThan Empty = new GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanIfDimensionGreaterThanIfDimensionLessThan();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanIfDimensionGreaterThanIfDimensionLessThan $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanIfDimensionGreaterThanIfDimensionLessThan();
        }
        public GetImagingPolicyImagePolicyTransformationIfDimensionGreaterThanIfDimensionGreaterThanIfDimensionLessThan build() {
            return $;
        }
    }

}
