// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationSquareFitAndFillFillTransformationArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationSquareFitAndFillFillTransformationArgs Empty = new GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationSquareFitAndFillFillTransformationArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationSquareFitAndFillFillTransformationArgs $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationSquareFitAndFillFillTransformationArgs();
        }
        public GetImagingPolicyImagePolicyTransformationIfOrientationPortraitIfOrientationSquareFitAndFillFillTransformationArgs build() {
            return $;
        }
    }

}
