// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionGreaterThanIfOrientationSquareIfOrientationDefaultArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionGreaterThanIfOrientationSquareIfOrientationDefaultArgs Empty = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionGreaterThanIfOrientationSquareIfOrientationDefaultArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionGreaterThanIfOrientationSquareIfOrientationDefaultArgs $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionGreaterThanIfOrientationSquareIfOrientationDefaultArgs();
        }
        public GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionGreaterThanIfOrientationSquareIfOrientationDefaultArgs build() {
            return $;
        }
    }

}
