// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationSquare extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationSquare Empty = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationSquare();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationSquare $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationSquare();
        }
        public GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationPortraitIfDimensionLessThanIfOrientationSquare build() {
            return $;
        }
    }

}
