// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;

import com.pulumi.akamai.inputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationDefaultArgs;
import com.pulumi.akamai.inputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationLandscapeArgs;
import com.pulumi.akamai.inputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationPortraitArgs;
import com.pulumi.akamai.inputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationSquareArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationArgs Empty = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationArgs();

    @Import(name="default")
    private @Nullable Output<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationDefaultArgs> default_;

    public Optional<Output<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationDefaultArgs>> default_() {
        return Optional.ofNullable(this.default_);
    }

    @Import(name="landscape")
    private @Nullable Output<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationLandscapeArgs> landscape;

    public Optional<Output<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationLandscapeArgs>> landscape() {
        return Optional.ofNullable(this.landscape);
    }

    @Import(name="portrait")
    private @Nullable Output<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationPortraitArgs> portrait;

    public Optional<Output<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationPortraitArgs>> portrait() {
        return Optional.ofNullable(this.portrait);
    }

    @Import(name="square")
    private @Nullable Output<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationSquareArgs> square;

    public Optional<Output<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationSquareArgs>> square() {
        return Optional.ofNullable(this.square);
    }

    private GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationArgs() {}

    private GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationArgs(GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationArgs $) {
        this.default_ = $.default_;
        this.landscape = $.landscape;
        this.portrait = $.portrait;
        this.square = $.square;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationArgs $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationArgs();
        }

        public Builder(GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationArgs defaults) {
            $ = new GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationArgs(Objects.requireNonNull(defaults));
        }

        public Builder default_(@Nullable Output<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationDefaultArgs> default_) {
            $.default_ = default_;
            return this;
        }

        public Builder default_(GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationDefaultArgs default_) {
            return default_(Output.of(default_));
        }

        public Builder landscape(@Nullable Output<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationLandscapeArgs> landscape) {
            $.landscape = landscape;
            return this;
        }

        public Builder landscape(GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationLandscapeArgs landscape) {
            return landscape(Output.of(landscape));
        }

        public Builder portrait(@Nullable Output<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationPortraitArgs> portrait) {
            $.portrait = portrait;
            return this;
        }

        public Builder portrait(GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationPortraitArgs portrait) {
            return portrait(Output.of(portrait));
        }

        public Builder square(@Nullable Output<GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationSquareArgs> square) {
            $.square = square;
            return this;
        }

        public Builder square(GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationSquareArgs square) {
            return square(Output.of(square));
        }

        public GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationLandscapeIfDimensionEqualIfOrientationArgs build() {
            return $;
        }
    }

}
