// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyTransformationCompositeImageCircleImageTransformationCompoundTransformation extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyTransformationCompositeImageCircleImageTransformationCompoundTransformation Empty = new GetImagingPolicyImagePolicyTransformationCompositeImageCircleImageTransformationCompoundTransformation();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationCompositeImageCircleImageTransformationCompoundTransformation $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationCompositeImageCircleImageTransformationCompoundTransformation();
        }
        public GetImagingPolicyImagePolicyTransformationCompositeImageCircleImageTransformationCompoundTransformation build() {
            return $;
        }
    }

}
