// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;

import com.pulumi.akamai.inputs.GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundTransformationArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundArgs Empty = new GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundArgs();

    @Import(name="transformations")
    private @Nullable Output<List<GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundTransformationArgs>> transformations;

    public Optional<Output<List<GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundTransformationArgs>>> transformations() {
        return Optional.ofNullable(this.transformations);
    }

    private GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundArgs() {}

    private GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundArgs(GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundArgs $) {
        this.transformations = $.transformations;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundArgs $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundArgs();
        }

        public Builder(GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundArgs defaults) {
            $ = new GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundArgs(Objects.requireNonNull(defaults));
        }

        public Builder transformations(@Nullable Output<List<GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundTransformationArgs>> transformations) {
            $.transformations = transformations;
            return this;
        }

        public Builder transformations(List<GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundTransformationArgs> transformations) {
            return transformations(Output.of(transformations));
        }

        public Builder transformations(GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundTransformationArgs... transformations) {
            return transformations(List.of(transformations));
        }

        public GetImagingPolicyImagePolicyTransformationCompoundTransformationFitAndFillFillTransformationCompoundArgs build() {
            return $;
        }
    }

}
