// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionGreaterThanIfOrientationPortraitArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionGreaterThanIfOrientationPortraitArgs Empty = new GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionGreaterThanIfOrientationPortraitArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionGreaterThanIfOrientationPortraitArgs $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionGreaterThanIfOrientationPortraitArgs();
        }
        public GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionGreaterThanIfOrientationPortraitArgs build() {
            return $;
        }
    }

}
