// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionGreaterThanIfOrientationPortrait extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionGreaterThanIfOrientationPortrait Empty = new GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionGreaterThanIfOrientationPortrait();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionGreaterThanIfOrientationPortrait $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionGreaterThanIfOrientationPortrait();
        }
        public GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionGreaterThanIfOrientationPortrait build() {
            return $;
        }
    }

}
