// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionLessThanIfDimensionGreaterThan extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionLessThanIfDimensionGreaterThan Empty = new GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionLessThanIfDimensionGreaterThan();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionLessThanIfDimensionGreaterThan $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionLessThanIfDimensionGreaterThan();
        }
        public GetImagingPolicyImagePolicyTransformationCompoundTransformationIfDimensionLessThanIfDimensionGreaterThan build() {
            return $;
        }
    }

}
