// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;




public final class GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfDimensionDefaultIfOrientationLandscape extends com.pulumi.resources.InvokeArgs {

    public static final GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfDimensionDefaultIfOrientationLandscape Empty = new GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfDimensionDefaultIfOrientationLandscape();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfDimensionDefaultIfOrientationLandscape $;

        public Builder() {
            $ = new GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfDimensionDefaultIfOrientationLandscape();
        }
        public GetImagingPolicyImagePolicyTransformationIfDimensionEqualIfDimensionDefaultIfOrientationLandscape build() {
            return $;
        }
    }

}
