// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPropertyRulesBuilderRulesV20231030BehaviorClientCertificateAuthArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetPropertyRulesBuilderRulesV20231030BehaviorClientCertificateAuthArgs Empty = new GetPropertyRulesBuilderRulesV20231030BehaviorClientCertificateAuthArgs();

    @Import(name="clientCertificateAttributes")
    private @Nullable Output<List<String>> clientCertificateAttributes;

    public Optional<Output<List<String>>> clientCertificateAttributes() {
        return Optional.ofNullable(this.clientCertificateAttributes);
    }

    @Import(name="enable")
    private @Nullable Output<Boolean> enable;

    public Optional<Output<Boolean>> enable() {
        return Optional.ofNullable(this.enable);
    }

    @Import(name="enableClientCertificateValidationStatus")
    private @Nullable Output<Boolean> enableClientCertificateValidationStatus;

    public Optional<Output<Boolean>> enableClientCertificateValidationStatus() {
        return Optional.ofNullable(this.enableClientCertificateValidationStatus);
    }

    @Import(name="enableCompleteClientCertificate")
    private @Nullable Output<Boolean> enableCompleteClientCertificate;

    public Optional<Output<Boolean>> enableCompleteClientCertificate() {
        return Optional.ofNullable(this.enableCompleteClientCertificate);
    }

    @Import(name="locked")
    private @Nullable Output<Boolean> locked;

    public Optional<Output<Boolean>> locked() {
        return Optional.ofNullable(this.locked);
    }

    @Import(name="templateUuid")
    private @Nullable Output<String> templateUuid;

    public Optional<Output<String>> templateUuid() {
        return Optional.ofNullable(this.templateUuid);
    }

    @Import(name="uuid")
    private @Nullable Output<String> uuid;

    public Optional<Output<String>> uuid() {
        return Optional.ofNullable(this.uuid);
    }

    private GetPropertyRulesBuilderRulesV20231030BehaviorClientCertificateAuthArgs() {}

    private GetPropertyRulesBuilderRulesV20231030BehaviorClientCertificateAuthArgs(GetPropertyRulesBuilderRulesV20231030BehaviorClientCertificateAuthArgs $) {
        this.clientCertificateAttributes = $.clientCertificateAttributes;
        this.enable = $.enable;
        this.enableClientCertificateValidationStatus = $.enableClientCertificateValidationStatus;
        this.enableCompleteClientCertificate = $.enableCompleteClientCertificate;
        this.locked = $.locked;
        this.templateUuid = $.templateUuid;
        this.uuid = $.uuid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPropertyRulesBuilderRulesV20231030BehaviorClientCertificateAuthArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPropertyRulesBuilderRulesV20231030BehaviorClientCertificateAuthArgs $;

        public Builder() {
            $ = new GetPropertyRulesBuilderRulesV20231030BehaviorClientCertificateAuthArgs();
        }

        public Builder(GetPropertyRulesBuilderRulesV20231030BehaviorClientCertificateAuthArgs defaults) {
            $ = new GetPropertyRulesBuilderRulesV20231030BehaviorClientCertificateAuthArgs(Objects.requireNonNull(defaults));
        }

        public Builder clientCertificateAttributes(@Nullable Output<List<String>> clientCertificateAttributes) {
            $.clientCertificateAttributes = clientCertificateAttributes;
            return this;
        }

        public Builder clientCertificateAttributes(List<String> clientCertificateAttributes) {
            return clientCertificateAttributes(Output.of(clientCertificateAttributes));
        }

        public Builder clientCertificateAttributes(String... clientCertificateAttributes) {
            return clientCertificateAttributes(List.of(clientCertificateAttributes));
        }

        public Builder enable(@Nullable Output<Boolean> enable) {
            $.enable = enable;
            return this;
        }

        public Builder enable(Boolean enable) {
            return enable(Output.of(enable));
        }

        public Builder enableClientCertificateValidationStatus(@Nullable Output<Boolean> enableClientCertificateValidationStatus) {
            $.enableClientCertificateValidationStatus = enableClientCertificateValidationStatus;
            return this;
        }

        public Builder enableClientCertificateValidationStatus(Boolean enableClientCertificateValidationStatus) {
            return enableClientCertificateValidationStatus(Output.of(enableClientCertificateValidationStatus));
        }

        public Builder enableCompleteClientCertificate(@Nullable Output<Boolean> enableCompleteClientCertificate) {
            $.enableCompleteClientCertificate = enableCompleteClientCertificate;
            return this;
        }

        public Builder enableCompleteClientCertificate(Boolean enableCompleteClientCertificate) {
            return enableCompleteClientCertificate(Output.of(enableCompleteClientCertificate));
        }

        public Builder locked(@Nullable Output<Boolean> locked) {
            $.locked = locked;
            return this;
        }

        public Builder locked(Boolean locked) {
            return locked(Output.of(locked));
        }

        public Builder templateUuid(@Nullable Output<String> templateUuid) {
            $.templateUuid = templateUuid;
            return this;
        }

        public Builder templateUuid(String templateUuid) {
            return templateUuid(Output.of(templateUuid));
        }

        public Builder uuid(@Nullable Output<String> uuid) {
            $.uuid = uuid;
            return this;
        }

        public Builder uuid(String uuid) {
            return uuid(Output.of(uuid));
        }

        public GetPropertyRulesBuilderRulesV20231030BehaviorClientCertificateAuthArgs build() {
            return $;
        }
    }

}
