// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPropertyRulesBuilderRulesV20240813BehaviorLimitBitRateBitrateTable extends com.pulumi.resources.InvokeArgs {

    public static final GetPropertyRulesBuilderRulesV20240813BehaviorLimitBitRateBitrateTable Empty = new GetPropertyRulesBuilderRulesV20240813BehaviorLimitBitRateBitrateTable();

    /**
     * The unit of measurement, either `KBPS`, `MBPS`, or `GBPS`.
     * 
     */
    @Import(name="bitrateUnit")
    private @Nullable String bitrateUnit;

    /**
     * @return The unit of measurement, either `KBPS`, `MBPS`, or `GBPS`.
     * 
     */
    public Optional<String> bitrateUnit() {
        return Optional.ofNullable(this.bitrateUnit);
    }

    /**
     * The numeric indicator of the download rate.
     * 
     */
    @Import(name="bitrateValue")
    private @Nullable Double bitrateValue;

    /**
     * @return The numeric indicator of the download rate.
     * 
     */
    public Optional<Double> bitrateValue() {
        return Optional.ofNullable(this.bitrateValue);
    }

    private GetPropertyRulesBuilderRulesV20240813BehaviorLimitBitRateBitrateTable() {}

    private GetPropertyRulesBuilderRulesV20240813BehaviorLimitBitRateBitrateTable(GetPropertyRulesBuilderRulesV20240813BehaviorLimitBitRateBitrateTable $) {
        this.bitrateUnit = $.bitrateUnit;
        this.bitrateValue = $.bitrateValue;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPropertyRulesBuilderRulesV20240813BehaviorLimitBitRateBitrateTable defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPropertyRulesBuilderRulesV20240813BehaviorLimitBitRateBitrateTable $;

        public Builder() {
            $ = new GetPropertyRulesBuilderRulesV20240813BehaviorLimitBitRateBitrateTable();
        }

        public Builder(GetPropertyRulesBuilderRulesV20240813BehaviorLimitBitRateBitrateTable defaults) {
            $ = new GetPropertyRulesBuilderRulesV20240813BehaviorLimitBitRateBitrateTable(Objects.requireNonNull(defaults));
        }

        /**
         * @param bitrateUnit The unit of measurement, either `KBPS`, `MBPS`, or `GBPS`.
         * 
         * @return builder
         * 
         */
        public Builder bitrateUnit(@Nullable String bitrateUnit) {
            $.bitrateUnit = bitrateUnit;
            return this;
        }

        /**
         * @param bitrateValue The numeric indicator of the download rate.
         * 
         * @return builder
         * 
         */
        public Builder bitrateValue(@Nullable Double bitrateValue) {
            $.bitrateValue = bitrateValue;
            return this;
        }

        public GetPropertyRulesBuilderRulesV20240813BehaviorLimitBitRateBitrateTable build() {
            return $;
        }
    }

}
