// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.akamai.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPropertyRulesBuilderRulesV20240531BehaviorAudienceSegmentationCloudletPolicy extends com.pulumi.resources.InvokeArgs {

    public static final GetPropertyRulesBuilderRulesV20240531BehaviorAudienceSegmentationCloudletPolicy Empty = new GetPropertyRulesBuilderRulesV20240531BehaviorAudienceSegmentationCloudletPolicy();

    @Import(name="id")
    private @Nullable Integer id;

    public Optional<Integer> id() {
        return Optional.ofNullable(this.id);
    }

    @Import(name="name")
    private @Nullable String name;

    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    private GetPropertyRulesBuilderRulesV20240531BehaviorAudienceSegmentationCloudletPolicy() {}

    private GetPropertyRulesBuilderRulesV20240531BehaviorAudienceSegmentationCloudletPolicy(GetPropertyRulesBuilderRulesV20240531BehaviorAudienceSegmentationCloudletPolicy $) {
        this.id = $.id;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPropertyRulesBuilderRulesV20240531BehaviorAudienceSegmentationCloudletPolicy defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPropertyRulesBuilderRulesV20240531BehaviorAudienceSegmentationCloudletPolicy $;

        public Builder() {
            $ = new GetPropertyRulesBuilderRulesV20240531BehaviorAudienceSegmentationCloudletPolicy();
        }

        public Builder(GetPropertyRulesBuilderRulesV20240531BehaviorAudienceSegmentationCloudletPolicy defaults) {
            $ = new GetPropertyRulesBuilderRulesV20240531BehaviorAudienceSegmentationCloudletPolicy(Objects.requireNonNull(defaults));
        }

        public Builder id(@Nullable Integer id) {
            $.id = id;
            return this;
        }

        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        public GetPropertyRulesBuilderRulesV20240531BehaviorAudienceSegmentationCloudletPolicy build() {
            return $;
        }
    }

}
