// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class PropertyRules extends pulumi.CustomResource {
    /**
     * Get an existing PropertyRules resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PropertyRulesState, opts?: pulumi.CustomResourceOptions): PropertyRules {
        return new PropertyRules(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'akamai:Properties/propertyRules:PropertyRules';

    /**
     * Returns true if the given object is an instance of PropertyRules.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PropertyRules {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PropertyRules.__pulumiType;
    }

    /**
     * JSON Rule representation
     */
    public /*out*/ readonly json!: pulumi.Output<string>;
    public readonly rules!: pulumi.Output<outputs.Properties.PropertyRulesRule[] | undefined>;
    public readonly variables!: pulumi.Output<string | undefined>;

    /**
     * Create a PropertyRules resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PropertyRulesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PropertyRulesArgs | PropertyRulesState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as PropertyRulesState | undefined;
            inputs["json"] = state ? state.json : undefined;
            inputs["rules"] = state ? state.rules : undefined;
            inputs["variables"] = state ? state.variables : undefined;
        } else {
            const args = argsOrState as PropertyRulesArgs | undefined;
            inputs["rules"] = args ? args.rules : undefined;
            inputs["variables"] = args ? args.variables : undefined;
            inputs["json"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(PropertyRules.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PropertyRules resources.
 */
export interface PropertyRulesState {
    /**
     * JSON Rule representation
     */
    readonly json?: pulumi.Input<string>;
    readonly rules?: pulumi.Input<pulumi.Input<inputs.Properties.PropertyRulesRule>[]>;
    readonly variables?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PropertyRules resource.
 */
export interface PropertyRulesArgs {
    readonly rules?: pulumi.Input<pulumi.Input<inputs.Properties.PropertyRulesRule>[]>;
    readonly variables?: pulumi.Input<string>;
}
