// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Inputs
{

    public sealed class GetImagingPolicyImagePolicyTransformationCompoundTransformationIfOrientationSquareIfOrientationInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("default")]
        public Input<Inputs.GetImagingPolicyImagePolicyTransformationCompoundTransformationIfOrientationSquareIfOrientationDefaultInputArgs>? Default { get; set; }

        [Input("landscape")]
        public Input<Inputs.GetImagingPolicyImagePolicyTransformationCompoundTransformationIfOrientationSquareIfOrientationLandscapeInputArgs>? Landscape { get; set; }

        [Input("portrait")]
        public Input<Inputs.GetImagingPolicyImagePolicyTransformationCompoundTransformationIfOrientationSquareIfOrientationPortraitInputArgs>? Portrait { get; set; }

        [Input("square")]
        public Input<Inputs.GetImagingPolicyImagePolicyTransformationCompoundTransformationIfOrientationSquareIfOrientationSquareInputArgs>? Square { get; set; }

        public GetImagingPolicyImagePolicyTransformationCompoundTransformationIfOrientationSquareIfOrientationInputArgs()
        {
        }
        public static new GetImagingPolicyImagePolicyTransformationCompoundTransformationIfOrientationSquareIfOrientationInputArgs Empty => new GetImagingPolicyImagePolicyTransformationCompoundTransformationIfOrientationSquareIfOrientationInputArgs();
    }
}
