// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Inputs
{

    public sealed class GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfOrientationInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("default")]
        public Input<Inputs.GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfOrientationDefaultInputArgs>? Default { get; set; }

        [Input("landscape")]
        public Input<Inputs.GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfOrientationLandscapeInputArgs>? Landscape { get; set; }

        [Input("portrait")]
        public Input<Inputs.GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfOrientationPortraitInputArgs>? Portrait { get; set; }

        [Input("square")]
        public Input<Inputs.GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfOrientationSquareInputArgs>? Square { get; set; }

        public GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfOrientationInputArgs()
        {
        }
        public static new GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfOrientationInputArgs Empty => new GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfOrientationInputArgs();
    }
}
