// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Inputs
{

    public sealed class GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationDefaultIfOrientationPortraitCompoundArgs : global::Pulumi.InvokeArgs
    {
        [Input("transformations")]
        private List<Inputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationDefaultIfOrientationPortraitCompoundTransformationArgs>? _transformations;
        public List<Inputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationDefaultIfOrientationPortraitCompoundTransformationArgs> Transformations
        {
            get => _transformations ?? (_transformations = new List<Inputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationDefaultIfOrientationPortraitCompoundTransformationArgs>());
            set => _transformations = value;
        }

        public GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationDefaultIfOrientationPortraitCompoundArgs()
        {
        }
        public static new GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationDefaultIfOrientationPortraitCompoundArgs Empty => new GetImagingPolicyImagePolicyPostBreakpointTransformationIfOrientationDefaultIfOrientationPortraitCompoundArgs();
    }
}
