// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Inputs
{

    public sealed class GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfDimensionDefaultIfOrientationArgs : global::Pulumi.InvokeArgs
    {
        [Input("default")]
        public Inputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfDimensionDefaultIfOrientationDefaultArgs? Default { get; set; }

        [Input("landscape")]
        public Inputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfDimensionDefaultIfOrientationLandscapeArgs? Landscape { get; set; }

        [Input("portrait")]
        public Inputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfDimensionDefaultIfOrientationPortraitArgs? Portrait { get; set; }

        [Input("square")]
        public Inputs.GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfDimensionDefaultIfOrientationSquareArgs? Square { get; set; }

        public GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfDimensionDefaultIfOrientationArgs()
        {
        }
        public static new GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfDimensionDefaultIfOrientationArgs Empty => new GetImagingPolicyImagePolicyPostBreakpointTransformationIfDimensionLessThanIfDimensionDefaultIfOrientationArgs();
    }
}
