// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Inputs
{

    public sealed class GetImagingPolicyImagePolicyTransformationIfDimensionLessThanIfOrientationDefaultCompoundTransformationInputArgs : global::Pulumi.ResourceArgs
    {
        public GetImagingPolicyImagePolicyTransformationIfDimensionLessThanIfOrientationDefaultCompoundTransformationInputArgs()
        {
        }
        public static new GetImagingPolicyImagePolicyTransformationIfDimensionLessThanIfOrientationDefaultCompoundTransformationInputArgs Empty => new GetImagingPolicyImagePolicyTransformationIfDimensionLessThanIfOrientationDefaultCompoundTransformationInputArgs();
    }
}
