// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Inputs
{

    public sealed class GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfDimensionInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("default")]
        public Input<Inputs.GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfDimensionDefaultInputArgs>? Default { get; set; }

        [Input("dimension")]
        public Input<string>? Dimension { get; set; }

        [Input("dimensionVar")]
        public Input<string>? DimensionVar { get; set; }

        [Input("equal")]
        public Input<Inputs.GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfDimensionEqualInputArgs>? Equal { get; set; }

        [Input("greaterThan")]
        public Input<Inputs.GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfDimensionGreaterThanInputArgs>? GreaterThan { get; set; }

        [Input("lessThan")]
        public Input<Inputs.GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfDimensionLessThanInputArgs>? LessThan { get; set; }

        [Input("value")]
        public Input<string>? Value { get; set; }

        [Input("valueVar")]
        public Input<string>? ValueVar { get; set; }

        public GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfDimensionInputArgs()
        {
        }
        public static new GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfDimensionInputArgs Empty => new GetImagingPolicyImagePolicyTransformationIfDimensionDefaultIfDimensionLessThanIfDimensionInputArgs();
    }
}
