// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Inputs
{

    public sealed class GetPropertyRulesBuilderRulesV20231030BehaviorStandardTlsMigrationArgs : global::Pulumi.InvokeArgs
    {
        [Input("allowHttpsDowngrade")]
        public bool? AllowHttpsDowngrade { get; set; }

        [Input("allowHttpsUpgrade")]
        public bool? AllowHttpsUpgrade { get; set; }

        [Input("cacheSharingDuration")]
        public int? CacheSharingDuration { get; set; }

        [Input("cacheSharingStartTime")]
        public string? CacheSharingStartTime { get; set; }

        [Input("enabled")]
        public bool? Enabled { get; set; }

        [Input("isCertificateSniOnly")]
        public bool? IsCertificateSniOnly { get; set; }

        [Input("isTieredDistributionUsed")]
        public bool? IsTieredDistributionUsed { get; set; }

        [Input("locked")]
        public bool? Locked { get; set; }

        [Input("migrationDuration")]
        public int? MigrationDuration { get; set; }

        [Input("migrationFrom")]
        public string? MigrationFrom { get; set; }

        [Input("migrationStartTime")]
        public string? MigrationStartTime { get; set; }

        [Input("tdLocation")]
        public string? TdLocation { get; set; }

        [Input("templateUuid")]
        public string? TemplateUuid { get; set; }

        [Input("uuid")]
        public string? Uuid { get; set; }

        public GetPropertyRulesBuilderRulesV20231030BehaviorStandardTlsMigrationArgs()
        {
        }
        public static new GetPropertyRulesBuilderRulesV20231030BehaviorStandardTlsMigrationArgs Empty => new GetPropertyRulesBuilderRulesV20231030BehaviorStandardTlsMigrationArgs();
    }
}
