// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Inputs
{

    public sealed class GetPropertyRulesBuilderRulesV20230920BehaviorStandardTlsMigrationInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowHttpsDowngrade")]
        public Input<bool>? AllowHttpsDowngrade { get; set; }

        [Input("allowHttpsUpgrade")]
        public Input<bool>? AllowHttpsUpgrade { get; set; }

        [Input("cacheSharingDuration")]
        public Input<int>? CacheSharingDuration { get; set; }

        [Input("cacheSharingStartTime")]
        public Input<string>? CacheSharingStartTime { get; set; }

        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("isCertificateSniOnly")]
        public Input<bool>? IsCertificateSniOnly { get; set; }

        [Input("isTieredDistributionUsed")]
        public Input<bool>? IsTieredDistributionUsed { get; set; }

        [Input("locked")]
        public Input<bool>? Locked { get; set; }

        [Input("migrationDuration")]
        public Input<int>? MigrationDuration { get; set; }

        [Input("migrationFrom")]
        public Input<string>? MigrationFrom { get; set; }

        [Input("migrationStartTime")]
        public Input<string>? MigrationStartTime { get; set; }

        [Input("tdLocation")]
        public Input<string>? TdLocation { get; set; }

        [Input("templateUuid")]
        public Input<string>? TemplateUuid { get; set; }

        [Input("uuid")]
        public Input<string>? Uuid { get; set; }

        public GetPropertyRulesBuilderRulesV20230920BehaviorStandardTlsMigrationInputArgs()
        {
        }
        public static new GetPropertyRulesBuilderRulesV20230920BehaviorStandardTlsMigrationInputArgs Empty => new GetPropertyRulesBuilderRulesV20230920BehaviorStandardTlsMigrationInputArgs();
    }
}
