// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Inputs
{

    public sealed class GetPropertyRulesBuilderRulesV20240212CriterionClientCertificateInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies custom handling of requests if any of the checks in the `enforceMtlsSettings` behavior fail. Enable this and use with behaviors such as `logCustom` so that they execute if the check fails. You need to add the `enforceMtlsSettings` behavior to a parent rule, with its own unique match condition and `enableDenyRequest` option disabled.
        /// </summary>
        [Input("enforceMtls")]
        public Input<bool>? EnforceMtls { get; set; }

        /// <summary>
        /// Executes rule behaviors only if a client certificate authenticates requests.
        /// </summary>
        [Input("isCertificatePresent")]
        public Input<bool>? IsCertificatePresent { get; set; }

        /// <summary>
        /// Matches whether the certificate is `VALID` or `INVALID`. You can also `IGNORE` the certificate's validity.
        /// </summary>
        [Input("isCertificateValid")]
        public Input<string>? IsCertificateValid { get; set; }

        /// <summary>
        /// Indicates that your Akamai representative has locked this behavior or criteria so that you can't modify it. This option is for internal usage only.
        /// </summary>
        [Input("locked")]
        public Input<bool>? Locked { get; set; }

        /// <summary>
        /// This option is for internal usage only.
        /// </summary>
        [Input("templateUuid")]
        public Input<string>? TemplateUuid { get; set; }

        /// <summary>
        /// A uuid member indicates that at least one of its component behaviors or criteria is advanced and read-only. You need to preserve this uuid as well when modifying the rule tree. This option is for internal usage only.
        /// </summary>
        [Input("uuid")]
        public Input<string>? Uuid { get; set; }

        public GetPropertyRulesBuilderRulesV20240212CriterionClientCertificateInputArgs()
        {
        }
        public static new GetPropertyRulesBuilderRulesV20240212CriterionClientCertificateInputArgs Empty => new GetPropertyRulesBuilderRulesV20240212CriterionClientCertificateInputArgs();
    }
}
