// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akamai.Inputs
{

    public sealed class RequestClientHintsArgs : global::Pulumi.InvokeArgs
    {
        [Input("acceptChes")]
        private List<string>? _acceptChes;
        public List<string> AcceptChes
        {
            get => _acceptChes ?? (_acceptChes = new List<string>());
            set => _acceptChes = value;
        }

        [Input("acceptCriticalChes")]
        private List<string>? _acceptCriticalChes;
        public List<string> AcceptCriticalChes
        {
            get => _acceptCriticalChes ?? (_acceptCriticalChes = new List<string>());
            set => _acceptCriticalChes = value;
        }

        [Input("locked")]
        public bool? Locked { get; set; }

        [Input("reset")]
        public bool? Reset { get; set; }

        [Input("templateUuid")]
        public string? TemplateUuid { get; set; }

        [Input("uuid")]
        public string? Uuid { get; set; }

        public RequestClientHintsArgs()
        {
        }
        public static new RequestClientHintsArgs Empty => new RequestClientHintsArgs();
    }
}
